### PR TITLE
update security issues

### PR DESCRIPTION
**Pull request by thetif**
This PR fixes a security vulnerability in api and web that is blocking all of our PRs from building.

### This pull request changes...

- adds script to call `npx npm-force-resolutions` preinstall
- adds a resolutions section to the package.json with the version of the dependency that fixes the vulnerability

### This feature is done when...

- [x] Product has approved the experience

### CODE REVIEW

**Review by knollfear — APPROVED** [review]
Worked locally for me.  LGTM.

**Review by cthulhuplus — APPROVED** [review]
LGTM

**Review by beparticular — APPROVED** [review]

**Review by NAretakis — COMMENTED** [review]
This is good to go, thank you!

**Review by NAretakis — APPROVED** [review]
Approved.

**Pull request merged**
