### PR TITLE
Tbolt/3571 delete certification

### LINKED ISSUE #3571: [Feature] Add delete certification letter to the frontend
**Description and related issues -**
Federal Admins should be able to delete certification that have not yet been matched. Connect to the end made in #3261.
### Acceptance criteria

- the delete button appears in the certification letter table next to certification letters with the status of unmatched
- clicking the button will open a modal
- clicking cancel in the modal will close the modal and do nothing else
- clicking delete in the modal will call the endpoint #3261
- when it has been successfully deleted, it should no longer show up in the table

### This task is done when…

This could include:

- [ ] all acceptance criteria are met
- [ ] tests are written to confirm acceptance criteria
- [ ] identify 508 considerations and/or recommendations

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #3571 

**Description-**
- Adds ability to Delete a uploaded or unmatched state admin delegation letter

**Steps to manually verify this change...**

1. Login as fed admin
2. Upload one or more certifications using the form
3. Delete those certifications
4. Verify they are no longer listed in the UI

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good

**Review by Sun-Mountain — APPROVED** [review]
CONFIRMED:

| Given         | When     | Then   | Result     | 
|--------------|-----------|------------|------------|
| the user adds a letter | the letter matches an existing applicable user | button appears in the row | ✅ PASS|
| the user deletes a letter | the letter and the applicable user are deleted | the letter and the user no longer appear in the UI | ✅ PASS|

**Review by jeromeleecms — COMMENTED** [review]
Overall looks good. Need your thoughts on this - once we delete the file, the link is still active. Do we need to update the file link / location in the database as part of the archive/deletion process?

**Comment by tbolt** [comment]
@jeromeleecms good catch, ill work with Tif on a way to handle this.

**Review by akuas — APPROVED** [review]
This works like intended. I was able to delete a certification, but I was wondering if there is a max file size for the letter. I had trouble adding some PDFs and 1 file I uploaded took a long while to appear.

**Comment by thetif** [comment]
@jeromeleecms I think that's a good idea but it's outside of the scope of this ticket. Could you create another ticket that we could look into this in the future when we have more users using this feature?

**Review by jeromeleecms — APPROVED** [review]
Sounds good - I'll create a separate issue for the name change.

**Pull request merged**
