### PR TITLE
tbolt/3338 Fix bug with activity summary

### LINKED ISSUE #3338: [Bug] Activity Summary displaying incorrectly in Executive Summary
**Description-**
The HTML in the Activity Summary is being displayed in the Executive Summary. 

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. login as em@il.com
2. open APD
3. expand activities
4. expand Activity 1
5. edit Activity short description in Activity Overview
6. click on Executive Summary

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [X] State Staff
- [X] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] All
- [ ] Firefox
- [ ] Chrome

**Expected results-**
Should see the short description with formatted text.

**Actual results-**
See the short description with the HTML printed out

### PR DESCRIPTION
**Pull request by tbolt**
resolves #3338 

**Description-**

**This pull request changes...**

- Updates the Activity Summary on the Executive Summary page to properly render HTML
- No side effects expected

**This pull request was tested in the follow ways…**

- Add richly-formatted text (bold text, image, etc...) to any Activity Summary
- Verify that when viewing the previously entered activity summary on the executive summary page it's rendering properly and not displaying html tags (such as `<p>` or `<strong>`)

**Steps to manually verify this change...**

1. Login with any user that can view APDs
2. Navigate to an activities activity overview page
3. Enter some richly-formatted text such as **bold**
4. Verify that in the executive summary it is rendering properly and not displaying html tags

### This pull request is ready to review when...

- [x] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mirano-darren** [comment]
It works, nice job!
image

**Comment by chris-miraflor** [comment]
Looks good to me!
image

**Review by chris-miraflor — APPROVED** [review]
Looks good to me!
image

**Review by thetif — APPROVED** [review]
LGTM

**Review by beparticular — APPROVED** [review]

**Pull request merged**
