### PR TITLE
Tbolt/2675 rich text editor lables

### LINKED ISSUE #2675: [Dev] [508] Correctly label rich text editors with their respective headings
As noted in the 508 Compliance review:
> Form field label for example “Program Introduction” should be associated with input text box so that screen reader can render the label upon receiving keyboard focus.

The "Program Introduction" section provides a TinyMCE rich-text editing input. Currently when the rich text area receives keyboard focus it announces **Rich Text Area. Press ALT-0 for help.** which does not describe what the rich text area is for. @radavis opened a ticket with TinyMCE-React to provide some support for this:
https://github.com/tinymce/tinymce-react/issues/177

### This task is done when…
 - [ ] Rich text editors have appropriate labels that are announced when keyboard focus is received

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2675 

### Description
Adds more descriptive labels to the Rich Text editor. See original ticket for full details and backstory.

### Significant changes or possible side effects
No significant changes or possible side effects as far as I know

### Automated test cases written
Snapshots updated

### Steps to manually verify this change

1. Login and view an APD
2. Use a screen reader
3. Verify that when focusing/selecting a rich text editor field, a descriptive title is read

### This pull request is ready to review when

- [ ] Automated tests are updated (and all tests are passing)
- [ ] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when

- [x] Code has been reviewed by someone other than the original author
- [ ] QA has verified the functionality related to the change
- [ ] QA has verified the accessibility using tools such as screen readers and
      WAVE (accessibility evaluation tool)
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Comment by mirano-darren** [comment]
Looks good to me!
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| TinyMCE text boxes  | on Staging (not this PR)  | Confirmed behavior described in the original ticket  | expected behavior, PASS ✅   |
| TinyMCE text boxes  | on this PR | All text boxes have a correct label. When using a screen reader there is now a more detailed description of the text box that gets focused  | PASS ✅   |

**Review by jeromeleecms — COMMENTED** [review]
Should all Rich text editors provide the voice over label? Sometimes I get the description and sometimes I don't have NVDA. I'm OK with moving this if the language for the description is in the page (as it could be a bug with NVDA).

**Review by jeromeleecms — APPROVED** [review]
This appears to be an issue with NVDA as the rest of the screen readers are picking up the description. We will have to test with a newer version of NVDA if possible and log this as a bug. @tbolt @mirano-darren is that OK with you?

**Comment by mirano-darren** [comment]
I believe I have the newest version of NVDA, but I will make the bug nonetheless

**Comment by tbolt** [comment]
@jeromeleecms That works for me. Thanks

**Review by beparticular — APPROVED** [review]

**Pull request merged**
