### PR TITLE
Knollfear/3091 use okta data affiliations

### LINKED ISSUE #3091: [Dev] Use Local Okta User data instead of contacting Okta when populating affiliations
### Feature -  
When the affiliations are fetched from the database we are currently requesting some additional data from Okta.  Once #3089 is complete we can and should pull that data from the local DB table.  For affiliations where we have okta user data we should include that data in query result when finding affiliations.  For users that we do not have Okta data for we should ping Okta and store that data for the next time.  

### This task is done when…
 - [ ] requesting an affiliation does not contact Okta unless we do not have the data locally
 - [ ] Data for users that we do not have is added to the DB when fetched from Okta.

### PR DESCRIPTION
**Pull request by knollfear**
resolves #3091

**Description-**

**This pull request changes...**

-pulls Okta User data from the local database instead of Okta
- stores additional okta_users data in the seed process.

**This pull request also touches…**

- any time affiliation lists are fetched

**This pull request was tested in the follow ways…**

- Log in as different types of admin and go to the state admin page.
- Updated unit tests to account for the removal of requests to okta

**Steps to manually verify this change...**

1. Update the DB for any user to have a different email or phone number
2. In this version the updated number will show on the state admin page.  In older versions the data in the DB is not read, so changing it will have no effect.
3. In another ticket in this branch okta data is captured on login so if you log in know that your okta data may change.

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Update the CHANGELOG

Looks good though

**Comment by thetif** [comment]
@knollfear could you add another migration making user_id the primary key for okta_users? I should have caught that the first time around, but apparently if you don't have a primary key set, pgAdmin locks all of the columns and won't let you edit them.

**Comment by thetif** [comment]
Test using the method that Mike suggested above. Everything appears to be working. I also tested logging in with the changed user again and the values are updated from Okta as expected. Looks good.

**Review by NAretakis — APPROVED** [review]
Good to go.

**Pull request merged**
