### PR TITLE
Tbolt/3204 manage account updates

### LINKED ISSUE #3204: [Feature] Update form for user to request additional states
Design task #3160

**Description and related issues -**
Update the the Manage Account component created in #2582 to reflect the new Figma mock ups below. You could also incorporate the bug created in #3194 into this work.

**Mockups or link to Figma**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3771%3A146

### This task is done when…

This could include:

- [ ] update the Manage Account component to match the mock ups
- [ ] all acceptance criteria are met

### PR DESCRIPTION
**Pull request by tbolt**
resolves #3204 

**Description-**

**This pull request changes...**

- Updates the Manage Account page to support the new designs

**Steps to manually verify this change...**

1. Login with any account
2. Navigate to **Manage Account** page
3. Verify Existing Affiliation are appearing by respective status
4. Verify design aligns with proposed figma designs (see original ticket)

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by thetif** [comment]
Ty is this using Knoll's affiliations endpoint? When I added an affiliation and closed it and then opened it again it didn't see the new affiliation until after I refreshed.

**Review by thetif — APPROVED** [review]
Looks good

**Comment by thetif** [comment]
Tested by:

|Given|When|Then|Result|
|---|---|---|---|
|the user does not have an affiliation|when they login the first they|they are asked to select and affiliation|:white_check_mark: PASS|
|the user only has one requested affiliation|when they click manage account|they can see their existing requested affiliation|:white_check_mark: PASS|
|the user only has one active affiliation|when they click manage account|they can see their existing active affiliation|:white_check_mark: PASS|
|the user only has one denied affiliation|when they click manage account|they can see their existing denied affiliation|:white_check_mark: PASS|
|the user only has one revoked affiliation|when they click manage account|they can see their existing revoked affiliation|:white_check_mark: PASS|
|the user is on manage account|they haven't entered a state|the submit button is disabled|:white_check_mark: PASS|
|the user is on manage account and requests a state|they click submit|they are redirected to the thank you page|:white_check_mark: PASS|
|the user requested an account and didn't refresh|when they request the same state|then the system throws an error|:x: **FAIL** will be fixed in #3264|
|the user is on manage account and requests multiple states|they click submit|they are redirected to the thank you page|:white_check_mark: PASS|
|the user is on the manage account page|they click the Back to Login link|nothing happens|:x: **FAIL** should be fixed in #3234|
|the user is on the manage account page|they select a state and click Back to Login|nothing happens|:x: **FAIL** should be fixed in #3234|

**Comment by akuas** [comment]
https://user-images.githubusercontent.com/57009131/125132386-3f9deb00-e0d2-11eb-8d2a-d3c8e149ba77.mov

I'm not sure if this is known but after you select a state affiliation, submit it, and return to manage account page, the new pending state is not updated immediately. It took about a minute for American Samoa to show up as pending. This doesn't feel like a problem really but I wanted to bring this to your attention before I approve the ticket @tbolt

**Comment by thetif** [comment]
@akuas that is known. There is a ticket #3264 to make sure it's updated every time that modal opens

**Review by jeromeleecms — APPROVED** [review]
@akuas I asked exactly the same question yesterday to Mike! But sounds good @thetif - as long as the issue is logged, this lines up with the new styling. 

Also screen reader picks up new design fine. Only odd thing when reading multiple states, it just reads them all in a list without pausing between them, but it's not "wrong."

**Review by akuas — APPROVED** [review]

**Comment by akuas** [comment]
@thetif @jeromeleecms Thanks, that good to know that y'all already flagged it. Hopefully, it read the header before the states listed below it.

**Comment by tbolt** [comment]
@jeromeleecms That's a good point. I did update some of the headings to use heading levels 1-3 (<h1><h2><h3>). I had considered having them be lists but I figured the design system provides the badges to sort of "live on their own." When I navigate to the list of affiliations I have to arrow down to go between them. I wasn't able to get to them all to read at once.

**Pull request merged**
