### PR TITLE
IE11 fix

### LINKED ISSUE #2601: Blank page loaded while using Non-Supported Browser IE
During 508 testing, it was discovered that IE11 would not load the application, and would only display a blank page.

https://github.com/CMSgov/eAPD/blob/master/web/src/util/browser.js declares that visiting our application in IE11 should allow for basic functionality, "though more advanced features and some visual styles may be broken."

We should discuss if IE11 support is necessary, then, fix webpack settings to allow for IE11 support and include it when testing preview deploys, or move IE11 to "Red".

### This task is done when...
 - [ ] Page is loaded with proper warning that browser is not supported

### PR DESCRIPTION
**Pull request by radavis**
Resolves #2601 

### This pull request...

- makes IE11 show the App again, instead of a blank page

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design ~has approved the experience~ does not have access to IE11
- [x] Product has approved the experience

### CODE REVIEW

**Comment by radavis** [comment]
This changes some babel/webpack settings which affects how the application code is built. It would be great if people could check out the preview deploy, and report back with the browser and browser version they used to view the app.

**Comment by CSwartzHMA** [comment]
image

This is what I see in version 11.1304.17134.0; Update Versions: 11.0.175

**Review by jeromeleecms — APPROVED** [review]
This seems to work as indicated - tested through the login process with
1) IE 11
2) Chrome 87
3) Edge 88
4) Firefox 78

Switch to IE 10 emulation results in a blank screen (which is what I was expecting)

**Review by tbolt — APPROVED** [review]
Tested with IE11 and I do see the page with the browser warning 👍

**Pull request merged**
