### PR TITLE
Add bulleted lists, numbered lists, formatting dropdown to the RichText editor

### LINKED ISSUE #2521: Add option to format or remove formatting in tinymce fields
In our re-pilot test we got feedback from the state and the reviewer the that messy formatting from copy/pasting from Word into the editor was unprofessional, not clear, and confusing to read. 

Before release, lets add in the ability for users to format their copy/pasted text or remove formatting from their copy/paste text so they can have a clear and uniform style in their APD documentation. 
(Related #2404)

### This task is done when...
 - [ ] Functionality has been added to tinymce for the user to change formatting in their copy/pasted text

### PR DESCRIPTION
**Pull request by radavis**
Resolves #2521

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Comment by beparticular** [comment]
@radavis I think adding these two could go a long way. 
forecolor
strikethrough

Also, lists seem to be important in APDs, so the list plug would be another good addition. 
https://www.tiny.cloud/docs/plugins/lists/


I'm still thinking about the format remove tool since it doesn't seem to be very useful. Will get back to you on that.

**Comment by radavis** [comment]
@beparticular Please see the preview deploy site for your requested changes.

**Comment by beparticular** [comment]
@radavis those work great, thank you. 

After a little more testing, can we remove the format remove button since it doesn't really serve a strong purpose? 

Sorry for the ask to do that and then needing to roll it back, but I think that feature is not at all what I was expecting based on their documentation. 

FWIW, this will also get us close to closing out issue #2404.

**Comment by radavis** [comment]
@beparticular No worries. I'm happy to add/remove tinymce plugins so that we can figure out which ones are actually useful.

I'll make those changes and move this PR from a draft, to ready for review.

**Review by beparticular — APPROVED** [review]

**Review by thetif — APPROVED** [review]

**Review by CSwartzHMA — APPROVED** [review]
This will make a big difference in the user experience. Very exciting!

**Pull request merged**
