### PR TITLE
Tbolt/2785 left navbar issue

### LINKED ISSUE #2785: Left navbar not updating when adding new activities or providing a name
When adding an activity, the left navbar is not updating with the new activity unless you click into the activity OR you click away from the activity navbar.

Additionally, the navbar activity name does not update after providing a name within the activity overview.

Steps to reproduce:

1. Add new activity
2. Left navbar does not update with new activity

3. Click anywhere else, sidebar now updates with the new activity
4. Go back into activity overview for the new activity and type a name
5. Sidebar does not update to include new name (even after clicking away)

6. Only way for the new name in the left navbar to appear seems to be navigating away from the builder (dashboard or export view) and then coming back in to the builder.

Does not affect the export view/output, so putting this as a Sev 3.

### This task is done when…
This could include:
 - [ ] Adding an activity should also add an activity to the left navbar
 - [ ] Adding the activity name should update the left navbar 
- [ ] Design has signed off
- [ ] Product has signed off

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2785 

### This pull request changes...

- When adding a new activity it now immediately shows up in the nav 
- When removing an activity it immediately removes it from the nav
- When adding/updating the activity name it now shows up immediately in the nav

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [x] QA has approved the experience
- [x] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Comment by eStar386** [comment]
The functionality works as expected - verified side navigation bar displays the name of the activity on the screen.

**Review by eStar386 — APPROVED** [review]

**Review by beparticular — APPROVED** [review]

**Review by jeromeleecms — APPROVED** [review]
Resolves the bug - as described!

Not clear about the 508 implications for updating live text in multiple areas, but screen reader picks up content when navigating just fine.

**Comment by tbolt** [comment]
@jeromeleecms I'm not sure about that either, but I generally think this is the way to go as _not_ having the nav and title sync'd up could be more confusing.

**Comment by jeromeleecms** [comment]
@tbolt Def. agree - looking forward to seeing this one get merged in.

**Pull request merged**
