### PR TITLE
updated Activities label

### PR DESCRIPTION
**Pull request by thetif**
Updated the Add Activity label in the Nav

### This pull request changes...

- changed label from Add Activity to Activities Dashboard

### This is how to verify this change...

1. login
2. open an APD
3. expand the Activities menu in the side nav
4. see that the top label is now Activities Dashboard

### This pull request is ready to merge when...

- [x] This code has been reviewed by someone other than the original author
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by knollfear — APPROVED** [review]

**Review by tbolt — APPROVED** [review]

**Review by eStar386 — COMMENTED** [review]
@thetif @beparticular @jeromeleecms 

Should the name of the sub-navigation bar match the header? 
NavBar

**Comment by beparticular** [comment]
@eStar386 @thetif correct, the header on the page should also match the sub nav, as well as the label under the buttons. That label under the button would only be visible under Activity 1, Overview.

**Comment by thetif** [comment]
https://github.com/cmsgov/eapd/issues/3010#issuecomment-833586240

**Review by eStar386 — APPROVED** [review]
Approved and exemption documented in the issue.

**Review by eStar386 — APPROVED** [review]
Passes - Document Exemption

**Review by beparticular — APPROVED** [review]

**Pull request merged**
