### PR TITLE
Tbolt/2940 Updates to contractor form labels, descriptions, and more

### LINKED ISSUE #2940: [Dev] Improve field labels and help text on private contractor page
development task for #2925

Changes: 

110173832-366fdb00-7dcd-11eb-8c5c-8a8de7886aee

110174853-c82c1800-7dce-11eb-92ea-076b2db8d8da

1. Removed the header that instructed to "outline contracts by contract or vendor name" to reduce redundancy.  (This may have created some extra whitespace in the screenshot, re: chrome dev tools skills)

2. Removed the example box (no examples were included)

3. Changed field label from Contractor Name to "Private Contractor or Vendor Name"
3.5 This will also need to change once "done" is selected and the summary is showing
3.75 This will also need to change in the export view

4. Moved help text from example box under the Contractor or Vendor Name field label
"Provide the name of the private contractor or vendor. For planned procurements, generalize by resource name. For example, Computer Resources/TBD"

5. Change "Description of Services" to "Procurement Methodology and Description of Services"
5.5 This will also need to change once "done" is selected and the summary is showing
5.75 This will also need to change in the export view

6. Added help text to the Procurement Methodology and Description of Services field as agreed upon above to 
"Explain the procurement process for the contractor and the scope of their work. Provide justification for any non-competitive procurements." 

7. I'm not sure why this text is wrapping and the other text isn't, might be my chrome dev tools skills. Just verify that the help text all wraps the same on this page. It's also wrapping on the Total Contract Cost help text, not sure why it's not consistent.
 
Screen Shot 2021-03-05 at 4 22 33 PM

8. In the export view, the field for Procurement Methodology and Description of Services isn't showing in the export view if nothing is added to that field. This needs to match the summary above. If this needs to be a separate dev issue, that's cool, but thought since the export view had to be changed anyways, it might be appropriate here. 

### This task is done when…
 - [ ] the header `Outline contracts by contract or vendor name` has been removed
 - [ ] the blue example box has been removed
 - [ ] the field label has been changed from `Contractor Name` to `Private Contractor or Vender Name`
   - [ ] the label for unspecified Contractor should be changed from `Contractor name not specified` to `Private Contractor or Vender Name not specified`
   - [ ] the label in the export view has been updated
 - [ ] add help text under the Private Contractor or Vender Name label `Provide the name of the private contractor or vendor. For planned procurements, generalize by resource name. For example, Computer Resources/TBD.`
 - [ ] the field label has been changed from `Description of Services` to `Procurement Methodology and Description of Services`
   - [ ] the label for unspecified Description of services should be changed from `Description of services not specified` to `Procurement Methodology and Description of Services not specified`
   - [ ] the label in the export view has been updated
 - [ ] add help text under the Procurement Methodology and Description of Services label `Explain the procurement process for the contractor and the scope of their work. Provide justification for any non-competitive procurements.`
 - [ ] it has been verified that help text is all wrapping the same
 - [ ] the label and value for Procurement Methodology and Description of Services is visible on the export view

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2940 

### This pull request changes...
- Updates form field labels and descriptions for private contractor section in activities
- Adds labels to export view where needed
- Addresses some styling issues as specified in the original issue

### This is how to verify this change...
1. Login to PR build
2. Create a new activity
3. Verify Private contractor section matches the spec provided in the original issue
4. Verify export view matches the spec provided in the original issue

### This pull request is ready to merge when...

- [x] Develop has updated automated tests (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [x] QA has manually tested and created bugs for any issues found (beyond minor fixes)
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good

**Comment by eStar386** [comment]
Functional Issue: Private Contractor Web vs. Export view 
There is a difference between the export view and the user view. The export view shows the dates both pdf and using the export/submit functionality but the user view shows the text **date not specified.** 

Related Information: 
Browsers: Chrome, FireFox UserRoles:All applicable roles (excludes login error roles and fed admin)

Steps to Reproduce: 
1. Navigate to any activities and proceed to the private contractor page. 
2. Select the add a private contractor  button and improperly add dates. For example 11/2019  or  any invalid combo of MM/DD/YYYY

Expected Result: Date shows
Actual Results: Produces on the web view date not specified. However, the edit button shows the dates. 

Export (PDF VIEW)
Screen Shot 2021-04-30 at 3 40 35 PM

User View(EAPD app) 
export view of dates

**Comment by tbolt** [comment]
great catch @eStar386. I tested this in the staging environment and was able to reproduce this issue there as well. Given that, I think it could be a new bug ticket since it doesn't appear that this ticket/work _introduces_ that bug.

**Review by eStar386 — APPROVED** [review]
Document Exemption and create a new issue for the bug that was verified in staging by @tbolt. Please use the steps described in verify the change .

**Comment by beparticular** [comment]
@tbolt I'm having trouble accessing the test environment in order to review this. can you check on this please?

**Review by beparticular — APPROVED** [review]

**Pull request merged**
