### PR TITLE
Tbolt/2712 back to eapd link bug

### LINKED ISSUE #2712: Back to eAPD link at the top of the print preview page is missing
During a Beta Testing debrief, we discovered that the "< Back to eAPD link" at the top of the print preview page has gone missing.

This was described in #2117 and implemented in #2182.

We should put the link back to people can navigate back to their APD without having to go to the dashboard first.

### This task is done when...
 - [ ] Back to APD link has been restored to the top of the export page
 - [ ] Code has been reviewed by someone else
- [ ] Design signs off
- [ ] Product signs off
- [ ] Root cause and other potential issues have been identified

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2712 

### This pull request changes...

- Resolves bug where the Back to APD link on the print preview was not showing

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Review by jeromeleecms — COMMENTED** [review]
Did this fix affect where the anchor point for where the "^ Back to the Top" link at the bottom of the page went? When you click on the link, it doesn't take you all the way to top, only the top of the instruction box.

**Comment by tbolt** [comment]
@jeromeleecms This did affect the anchor point. Previously the "Back to Top" link was taking you to the Executive Summary section. I thought this was an improvement to that. We could update the "Back to Top" link to go somewhere else but right now it's consistent with where the "Skip Nav" goes (ie. goes to the "main content" of the page)

**Comment by jeromeleecms** [comment]
Understood - moving it higher in the page is a 👍.  

🤔 -> part of the intention for the back to top was to allow the user to go quickly back and go "back to APD" if they found they needed to make an edit during their review. @beparticular @tbolt should we make it a little higher so the "back to APD" is visible after clicking the back to top link?

**Comment by beparticular** [comment]
@jeromeleecms yes, I think it should go back up to the top so that the back to apd link shows

**Comment by jeromeleecms** [comment]
@tbolt How much of a lift it is to move the anchor point? As you noted in standup today, open to spinning up a separate issue to avoid scope creep on this one.

**Comment by tbolt** [comment]
@jeromeleecms I looked into this a bit more and the thing that is making it challenging is this: We have a "fixed" nav/header that doesn't move when you scroll. When I try to have the the "^ Back to the top" anchor to the actual "Return to APD" link it does so but the browser doesn't take into account the fixed nav/header so the "Return to APD" link ends up hidden behind the nav/header. Hope this makes sense. I am going to try to find some creative solutions now though. Will report back soon.

**Comment by beparticular** [comment]
@tbolt @cthulhuplus I'm not able to log in on the link for this issue

**Comment by cthulhuplus** [comment]
@beparticular I have rebuilt the instance in question and am now able to log in via this URL:
https://ec2-107-22-124-17.compute-1.amazonaws.com/

**Review by beparticular — APPROVED** [review]

**Review by jeromeleecms — APPROVED** [review]
Looks good!

**Pull request merged**
