### PR TITLE
Knollfear/3223 login check

### LINKED ISSUE #3223: Heartbeat Check before showing the login screen
As a user when the backend is down the current message I see is "Invalid username or password" because the login check fails.  This is not the most helpful message because it misleads me about the cause of my problems. We should check that our API and Okta are up before displaying the login screen so that the user will have a better understanding of they they cannot log in. Check that the API is up using the /heartbeat endpoint. Check that Okta is up using the web/src/util/auth.js - renewToken and add error handling to fail if the error is a 500. 

**mockup**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29116

### This task is done when...

- [ ] a check to the API healtcheck endpoint is preformed and is successful before showing the login screen
- [ ] a check to Okta is performed and is successful before showing the login screen

### PR DESCRIPTION
**Pull request by knollfear**
resolves #3223

**Description-**
implements a check to /heartbeat when painting the login screen.  If that check fails then the login screen is disabled.

**This pull request changes...**

- the login screen is disabled if the /heartbeat endpoint does not return a 200 response.

**This pull request also touches…**

Just the login page

- possible side effects of this change
none.  It should just affect the login page, and even then, only when it the api heartbeat enpoint returns 4XX or 5XX.
**This pull request was tested in the follow ways…**
added 1 automated test case and manual checks.

**Steps to manually verify this change...**

- start local containers and go to http://localhost:8080 to see the login screen as normal
- run docker ps to determine the running container ID's.  
- find the running container ID and stop it with "docker stop <container ID>"
- reload localhost:8080 to see the disabled view
- restart the containers and verify it is back to normal

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good!

**Comment by mirano-darren** [comment]
Looks good. Test went through as expected, and comparing the disabled view to the [mockup](https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=3996%3A29116) they are both the same. 

|Given|When|Then|Result|
|---|---|---|---|
|Accessed [http://localhost:8080](http://localhost:8080)|Local containers were started|Login screen appeared as normal|:white_check_mark: PASS|
|Get API Container ID|"docker ps"|"stop docker [container ID]"|:white_check_mark: PASS|
|Refresh [http://localhost:8080](http://localhost:8080)|API Container is stopped|Disabled view screen appears|:white_check_mark: PASS|
|Refresh [http://localhost:8080](http://localhost:8080)|Containers have been reset|Back to normal login screen|:white_check_mark: PASS|

**Review by jeromeleecms — APPROVED** [review]
I don't have the ability to test this on my local computer to run the tests. If Tif was able to successfully test/complete this, then I'm going to say this is GTG.

**Comment by thetif** [comment]
@jeromeleecms and @akuas here is what it looks like when you perform those steps above.

Screen Shot 2021-07-09 at 9 53 58 AM

Then, when the server comes back up and you refresh, it goes back to normal.

**Review by akuas — APPROVED** [review]
Didn't see an alert indicating that the system was down.

**Pull request merged**
