### PR TITLE
updated readme

### PR DESCRIPTION
**Pull request by thetif**
### This pull request changes...

- README.md to be updated with information about setting up Okta
- Changes the way we seed information to the database. Specifies the folders for the seeds for each environment. Moves the seed files inside their folder and renames them to main. Creates a seed for creating users. Changes the seed script to only run the main seed for the environment. Adds a seed script for just loading the users. Changed the way the database is created and destroyed in the tests.

### This pull request is ready to merge when...

~- [ ] Tests have been updated (and all tests are passing)~
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
~- [ ] Associated OpenAPI documentation has been updated~
~- [ ] Changelog is updated as appropriate~

### This feature is done when...

~- [ ] Design has approved the experience~
- [ ] Product has approved the experience

### CODE REVIEW

**Review by jeromeleecms — APPROVED** [review]
This seems fine.

**Comment by thetif** [comment]
Yeah this small README change turned into kind of an overhaul of seeding. Oops.

**Review by radavis — APPROVED** [review]
:+1:

**Review by tbolt — APPROVED** [review]
Looks good. All tests pass. Seed updates are very nice.

Prettier did modify a few items in `/web` if you wanted to update those in the PR

**Pull request merged**
