### PR TITLE
Tbolt/2935 login help links

### LINKED ISSUE #2935: [Dev] Add links from main login page so new users can access account creation instructions
Once docs are available in S3, we will need to add two links to the main login page - One for EUA Account instructions and one for System Access for new users who already have an EUA Account.

Dev task for #2821

Feature -  
Users need more information about how to handle problems with their account on the login page. Links need to be added to help the user reset passwords, create an EUA account, request EUA job codes, and get general help.

Add link under password input:
Forgot password? [Reset password at EUA](https://eua.cms.gov/iam/im/pub/cui7/index.jsp?task.tag=forgottenpasswordreset)

Add new users help text:
**New Users**
New users must have an EUA account with the correct job codes before logging into the system.

Add a link to getting started doc:
Need an EUA account? [How to Get Started.](<API_URL>/docs/account-registration)

Add a link to access eAPD doc:
Have an EUA account? [How to Access the eAPD](<API_URL>/docs/system-access)

Update the support email link text to:
Still need help? Email us at [CMS-EAPD@cms.hhs.gov](mailto:CMS-EAPD@cms.hhs.gov?subject=Password%20Recovery%20Request%20for%20eAPD)

### This task is done when…
 - [ ] there is a reset password link
 - [ ] there is help text for new users
 - [ ] there is a link to the getting started doc
 - [ ] there is a link to the access eAPD doc
 - [ ] updated the text for the support email

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2935 

### This pull request changes...

- Adds new help content and links to login page

### This is how to verify this change...
1. Navigate to preview build
2. Verify new content and links [match the design spec](https://images.zenhubusercontent.com/5f18484c4aa7386e0e7413c8/fedeeb41-e060-4a03-a045-55efca41af6d)
3. Verify links work as intended (some links work but the endpoint returns placeholder files. that is OK)

### This pull request is ready to merge when...

- [x] Develop has updated automated tests (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] QA has manually tested and created bugs for any issues found (beyond minor fixes)
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Review by eStar386 — APPROVED** [review]
Passes

**Comment by beparticular** [comment]
@tbolt it wasn't communicated in the original specs, but the intent for these was that people would open the PDFs in the browser instead of the documents automatically downloading. 

Would it be possible to change this so that the links open in the browser? 

cc @CSwartzHMA

**Review by NAretakis — APPROVED** [review]
Links work, good to go once @beparticular 's question of open in browser vs download is answered.

**Review by beparticular — APPROVED** [review]
Approving the interactions on the links - noting that link 1 appears to be the eAPD logo as a placeholder for the full document. cc @CSwartzHMA

**Comment by CSwartzHMA** [comment]
@beparticular It looks like the links are taking you to the incorrect pages. The first should go to where the second is taking you.  Both docs are posted, so not sure why the first is going to the logo.

**Comment by beparticular** [comment]
@tbolt please see Caryn's comment above

**Comment by tbolt** [comment]
@beparticular @CSwartzHMA this was addressed. The links should be going to the correct documents now.

Couple notes
* The forgot/reset password EUA link does not open in a new tab, this does a standard page navigation. 
* The method in which we are having the help docs(pdfs) open in a new tab makes some browsers interpret it as a pop-up. So a user may have to hit allow pop-up before being able to see it.

**Pull request merged**
