### PR TITLE
testing IE error

### PR DESCRIPTION
**Pull request by thetif**
resolves #3276 

**Description-**
Fixes the issue with not displaying in IE11. Now displays the warning to upgrade their browser.

**This pull request changes...**

- makes IE11 a red browser
- fixes issue with displaying the warning on IE11

**Steps to manually verify this change...**

1. open IE11
2. see warning to upgrade their browser

### This pull request is ready to review when...

- [X] Automated tests are updated (and all tests are passing)
- [X] The change has been documented
- [X] Changelog is updated as appropriate
- [X] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by mirano-darren** [comment]
Tested on IE11 and it works. Here's what it looks like:
image

**Review by tbolt — APPROVED** [review]
Updates look good. Warning does appear with IE11-

image

**Review by knollfear — APPROVED** [review]
looks good to me.  Confirmed experience on IE11, chrome, safari and Firefox.

**Review by jeromeleecms — APPROVED** [review]
Tested in IE 11, red browser warning appears. Tested in Chrome, Edge, Firefox - no warnings. Tested in Safari, yellow browser warning appears.

Works as advertised.

**Pull request merged**
