### PR TITLE
ends the timeout and closes the alert if the user does performs an action

### PR DESCRIPTION
**Pull request by thetif**
### This pull request changes...

- a modal should pop up and the user should not be able to escape or click outside of it to close it
- clicking the X button should close the modal and continue the session
- clicking Continue should continue the session
- clicking Sign out should sign the user out of the session and return them to the login screen

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
~- [ ] The change has been documented~
~- [ ] Associated OpenAPI documentation has been updated~
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by cthulhuplus — APPROVED** [review]
I have tested the functionality and it works as intended.

**Comment by jeromeleecms** [comment]
Waiting on review of this until we clarify if this is still needed after converting the existing dialogue box to a modal.

**Comment by cthulhuplus** [comment]
Tried it afresh. I was unable to escape the pop-up and was forced to interact with it.

**Review by beparticular — APPROVED** [review]
This all worked as expected! Hooray!

**Review by jeromeleecms — CHANGES_REQUESTED** [review]
Functionally this works correctly (tested on the dashboard) - running into some accessibility issues though:  

1) Screen reader is having a terrible time with it. When the modal appears, it reads the content of the modal (the time is way off) and then reads the page underneath... in a never ending cycle until an action is taken...

2) The focus state also seems to be resetting making it essentially impossible to navigate via keyboard. Tabbing while the dialog is open pushes the focus back to the close linking which is making a keyboard trap. Thoughts on how to fix this?

**Comment by thetif** [comment]
I will look into it.

**Review by jeromeleecms — APPROVED** [review]
Test this out with the new changes. Seems to solve most problems.

Talked to @thetif about the timer issue, we'll spin up an issue to have Ty look at best practice for how to present a countdown to screen reader users.

**Comment by thetif** [comment]
additional accessibility concerns will be addressed in #2738

**Review by radavis — APPROVED** [review]
Works as advertised on preview.

**Pull request merged**
