### PR TITLE
Nz/3714 dateform revamp

### LINKED ISSUE #3714: [Feature] Update Date Form Errors
**Description and related issues:**
Update Date Forms to take in a simplified error:

Also can address #[3682](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/cmsgov/eapd/3682)

**This task is done when...**

- [x] Simplified Date form takes in a single line error per iteration
- [x] Bug for year input fixed

### PR DESCRIPTION
**Pull request by Sun-Mountain**
Resolves #3714 

**Description-**

Update Date Forms to take in a simplified error.
Address Bug #3642.

**This pull request changes...**

- The simplification of the Date Field component
- Using the default `dateObject` to fix the aforementioned bug.

**This pull request also touches…**

- Merged in [3646](https://github.com/CMSgov/eAPD/pull/3719) to not have to deal with save issues.

**This pull request was tested in the follow ways…**

- Updating tests

**Steps to manually verify this change...**

1. The DateField 

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — COMMENTED** [review]
Code looks good

**Comment by thetif** [comment]
CONFIRMATION:

|Given|When|Then|Result|
|---|---|---|---|
|a date field|a valid date is entered|it is saved|:white_check_mark: PASS|
|a date field|an invalid date is entered|it is not saved|:white_check_mark: PASS|
|a date field|too many numbers are entered in the field|none of the other fields are accepted and it is not saved|:white_check_mark: PASS|
|a date field|when it already has a date|the date displays as expected|:x: FAIL|

**Comment by mirano-darren** [comment]
hmmm I think i did something wrong when checking out the branch then

**Review by tbolt — COMMENTED** [review]
good update using the design system classes instead of custom ones 👍

**Comment by mirano-darren** [comment]
Good work! Couple of small things:
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| a subform date field | a valid date is entered  | it is saved | ✅ PASS
| a subform date field | all fields are empty | the save button cannot be clicked | ✅ PASS
| a subform date field | only one day/month/year field is empty| the save button cannot be clicked | ✅ PASS
| a subform date field | a valid date is edited to another valid date | the date is updated | ✅ PASS
| a subform date field | a number less than 1 is entered | the number is considered valid | ❌ FAIL
| a subform date field | an invalid date is entered | error message appears, but save button is still clickable (see pic) | ❌ FAIL

image

**Comment by mirano-darren** [comment]
oops, the second to last test case, the then column should be "the number is considered invalid"

**Pull request merged**
