### PR TITLE
fixing storing of Okta data on login

### LINKED ISSUE #3242: [Bug] Information not being filed in for some users
**Description-**
I am not seeing the database get updated with the user's information when they login. It's also displaying empty information for the user in the federal admin

**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. log in as fedadmin
2. navigate to the Federal Admin portal
3. look at norole user in the requested tab
4. log out
5. log back in as norole
6. log out
7. log in again as fedamin
8. navigation to the Federal Admin portal
9. look at norole in the requested tab

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**
The user's information should be updated in the okta_users table whenever they login.

**Actual results-**
The data is not being updated when the user logs in.

**Logs or error output/Screenshot/Video-** (at least 1 of these)

### PR DESCRIPTION
**Pull request by knollfear**
Replacing code that went missing.  This is not at all new code, but rather code that got squashed in a merge conflict previously.

resolves #3242

**Description-**

**This pull request changes...**

- adds in a request for data from Okta to the /me endpoint

**This pull request also touches…**

- possible side effects of this change

none. This is all code that has been previously approved, it just seems to have disappeared in a merge conflict.

**This pull request was tested in the follow ways…**

- select * from okta_users to see what data exists for users in the DB
- alter data as you see fit
- log in and see if the data appears, or if it was altered is changed back

**Steps to manually verify this change...**

1. okta_user data is displayed on the affiliation request approval screen.  If a user has data on that table it will be on this screen.

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good, please add this to the changelog

**Review by tbolt — APPROVED** [review]
Works well.

**Comment by thetif** [comment]
Looks good, tested by:

| Given | When | Then | Result |
|---|---|---|---|
| The display name and phone number for norole were blank | logged in as norole | the database was updated with values from Okta | :white_check_mark: PASS |
| The display name and phone number for norole were changed to something different | logged in as norole | the database values were overwritten with values from Okta | :white_check_mark: PASS |

**Review by jeromeleecms — APPROVED** [review]
I don't have the tools to test this, but Ty and Tif are good with this (plus it worked before). Gtg.

**Pull request merged**
