### PR TITLE
Tbolt/2394 add tinymce to fields

### LINKED ISSUE #2394: Add tinymce editor to 2 fields
After our session with DE and watching them use the app, they mentioned expecting the tinymce editor in a couple of fields where it was missing. These were determined as fields that would need to be updated in an APD update. 
 
We looked through the app and determined which narrative fields don’t have, but may need the tinymce editor options:

Activities > Activity Overview short overview of the activity field
Activities > Private contractor costs > Description of Services

### This task is done when...
 - [ ] Product oks and prioritizes this change 
 - [ ] The editor is added to the prioritized fields (will be listed if there are any more than the above)

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2394 

### This pull request changes...

- Adds rich text editor to activity summary
- Adds rich text editor to private contractor costs. Also renders rich text in parent component

### This is how to verify this change...
1. Checkout branch or preview build
2. Verify that the activity summary/overview has been changed from a text field to a rich text field
3. Verify that under Private Contractor Costs the contractor description form has been changed from text field to rich text field
4. Verify that descriptions are displayed properly once saved

### This pull request is ready to merge when...

- [x] Developer has updated automated tests (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] QA has manually tested and created bugs for any issues found (beyond minor fixes)
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by tbolt** [comment]
@thetif if you could look at [this test](https://github.com/CMSgov/eAPD/pull/2965/files#diff-e9129482bfa6bb62ac1538f796839e2bc44357480d6551ac831f75da095fa8f9L194) in particular that would be great. I have it working but I'm not confident it's a great test and/or if its doing what it's supposed to.

**Review by thetif — APPROVED** [review]

**Comment by thetif** [comment]
That test looks good, it is testing what is supposed to be changing.

**Comment by eStar386** [comment]
Failed Functional Testing:

Steps to Reproduce 
Precondition: Using the 1.Private Contractor Page -> Description of Services. 2.Activity Dashboard -> Overview of Activity Field
1. Navigate to the specified Rich Text Editors listed above then Insert Text and Image.
2. Navigate to any other RTE, Insert the same text and image.
3. Navigate to Executive Summary: The images are not displaying, it shows the tag. 
4. Navigate to Activity: The images are not displaying, it shows the image tag.
5. Navigate to Export and Submit: View the pdf version images-The images are not displaying, it shows the image tag.

Actual Result: Images displayed only in the previous RTEs. 

Expected Result:  Images displayed in all RTEs in web and pdf versions.

**Comment by tbolt** [comment]
@eStar386 could this be a general issue with the rich text editors or do you think it's specific to the work I did in this ticket?

**Review by thetif — APPROVED** [review]

**Comment by tbolt** [comment]
@thetif or @knollfear do you mind double checking the use of dangerouslySetHTML? I'm not clear on where/how we are sanitizing the inputs and just want to be safe.

**Comment by thetif** [comment]
We are striping out the input from the APD on the backend, so it shouldn't be displaying anything dangerous.

**Review by eStar386 — APPROVED** [review]
Passes all previous test cases for RTE testing.  
Test Steps: Navigate to the APD overview and /or private contractor page (see steps to verify above)
1. Add images and Text
2. Verify export view 
 https://docs.google.com/spreadsheets/d/1LqdcfO6-VUGs3pSpoGu8XTv0O9euktNjmKC7FHbKJ3Q/edit?usp=sharing

**Review by beparticular — APPROVED** [review]

**Review by NAretakis — APPROVED** [review]
Rich text for all! Good to go.

**Pull request merged**
