### PR TITLE
Rename state cost category

### LINKED ISSUE #2432: Rename State Cost Category page and update Nav Bar to better assist users in navigation
Change log -
- Change nav label to State staff and expenses (from State cost categories)
- Change page header to State staff and expenses (from State cost categories)
- Change the FFP and Budget > Estimated Quarterly budget table first row to
State Staff and Expenses
(In-house Costs) (would be ideal for this to be on its own line for clarity)

Make sure the export view reflects the recent changes to the headers:
- Change "In-House Cost Categories: State Personnel" to
Correct "State staff"
- Change "In-House Cost Categories: Non-Personnel" to
Correct "Other state expenses"

Original design task #2390

### This task is done when...
 - [x] the navigation is updated according to the above
 - [x] the builder is updated according to the above
-  [x] the exporter is updated according to the above

### PR DESCRIPTION
**Pull request by thetif**
Rename State cost category
resolves #2432 

### This pull request changes...

 - Change nav label to State staff and expenses (from State cost categories)
 - Change page header to State staff and expenses (from State cost categories)
 - Change the FFP and Budget > Estimated Quarterly budget table first row to State Staff and Expenses (In-house Costs) (would be ideal for this to be on its own line for clarity)
 - Change "In-House Cost Categories: State Personnel" to Correct "State staff"
 - Change "In-House Cost Categories: Non-Personnel" to Correct "Other state expenses"

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
~- [ ] The change has been documented~
~- [ ] Associated OpenAPI documentation has been updated~
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Looks good

**Comment by CSwartzHMA** [comment]
@beparticular Confirming we still need the references to In-House Costs in the instructions and the example in the Estimated Quarterly Expenditures. I believe this was a reference to the previous section title, but also might be helpful context to new users who may be using this term in their current APD. 

If yes, then this one is ready to go from my perspective.

**Review by radavis — APPROVED** [review]
👍

**Comment by beparticular** [comment]
@CSwartzHMA I think the references are fine in the help text and example

**Review by beparticular — APPROVED** [review]

**Review by CSwartzHMA — APPROVED** [review]

**Pull request merged**
