### PR TITLE
Chris miraflor/3284 e2e tests key state personnel

### LINKED ISSUE #3284: [Feature] Create e2e tests for Key State Personnel
**Description and related issues -**
Write a test that creates and APD and fills in all of the fields in the Key State Personnel section.

### Test cases needed…

- [x] should be able to log in
- [x] should be able to create an APD
- [x] should be able add blank Key Personnel
    - [x] verify that there are 56 states in the State dropdown
    - [x] verify that when there are no Primary Contacts that there is a message that says "Primary Point of Contact has not been added for this activity."
    - [x] should be able to add a blank Primary Contact
        - [x] verify that clicking Add Key Personnel and then clicking Done will display default data for the Primary Point of Contact. Name is should be "Primary Point of Contact name not specified". Role should be "Role not specified". Total cost should be $0
    - [x] should be able to add a blank Key Personnel 
        - [x] verify that clicking Add Key Personnel and then clicking Done will display default data for the Key Personnel. Name should be "Key Personnel name not specified". Role should be "Role not specified". Total cost should be $0.
   - [x] should be able to add a blank Key Personnel that is chargeable to the project
        - [x] verify that clicking Add Key Personnel and then clicking Done will display default data for the Key Personnel. Name should be "Key Personnel name not specified". Role should be "Role not specified". FFY Cost, FTE, and Total should be 0 for all years.
- [x] should have default values in the export view
    - [x] verify that the Medicaid director Name, Email, and Phone don't have values
    - [x] verify that the Medicaid office address says "No response was provided"
    - [x] verify that Key Personnel and Program Management have the same default values from above plus a blank email address field
- [x] should be able to fill out the Key State Personnel page
    - [x] should be able to fill out the State Director and Office Address 
    - [x] should be able to delete a Key Personnel
        - [x] verify that there is no delete for the Primary Point of Contact
        - [x] verify that clicking delete on the Key Personnel opens a delete confirmation modal
        - [x] verify that clicking Cancel on the delete confirmation modal closes the modal but doesn't delete the Key Personnel
        - [x] verify that clicking Delete on the delete confirmation modal closes the modal and does delete the Key Personnel
    - [x] should be able to fill out Primary Point of Contact
        - [x] verify clicking edit opens the form again
        - [x] verify that values that were entered in the form are on the page after you click Done
    - [x] should be able to fill out Key Personnel
        - [x] verify that clicking edit opens the form again
        - [x] verify that checking Yes opens the form for FFY costs
        - [x] verify that values that were entered in the form are on the page after you click Done
    - [x] should go to Results of Previous Activities if you click Continue
- [x] should have the same data in the export view
    - [x] verify that the values displayed in the export view are the same as above

### PR DESCRIPTION
**Pull request by chris-miraflor**
resolves #3284 

**Description-**
Creates e2e cypress tests for filling out and exporting key personnel data for eAPD form.

**This pull request changes...**

- Adds folder for e2e tests in cypress/integration
- Adds tests for key personnel data in aforementioned new folder

**This pull request also touches…**

- Tests use the default `users.json` file in cypress fixtures.
- A Jest test for the APD state profile page where a typo caused the cypress test to throw an error. Fixing the typo then caused an error, but the Jest test had a fix applied for this.

**This pull request was tested in the follow ways…**

- Running cypress on the new test file

**Steps to manually verify this change...**

1. With this branch checked out, run `docker-up compose` in root folder
2. Run app, including migrate and seed commands
4. Run cypress with `npm run cy:open` or `npx cypress open` in /web
5. Run the test `02-key-state-personnel.spec.js` in the `apd` folder
6. All tests should pass

### This pull request is ready to review when...

- [X] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [X] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — CHANGES_REQUESTED** [review]
@chris-miraflor can you upload that users fixture? I think it got lost yesterday when we were cleaning up the PR

**Review by tbolt — APPROVED** [review]
Nice work. When I ran it the first time I saw a couple errors, re-running it I didn't see them, third run I saw them again. Seems inconsistent so maybe it's just a timing thing.
Screen Shot 2021-07-28 at 10 36 55 AM
Screen Shot 2021-07-28 at 10 37 08 AM

**Comment by chris-miraflor** [comment]
It looks like the inputted data for the personnel sometimes isn't saving, probably because there is no wait for one of them. I added a wait to the test case where data is inputted.

**Comment by chris-miraflor** [comment]
> Nice work. When I ran it the first time I saw a couple errors, re-running it I didn't see them, third run I saw them again. Seems inconsistent so maybe it's just a timing thing.
> Screen Shot 2021-07-28 at 10 36 55 AM
> Screen Shot 2021-07-28 at 10 37 08 AM

It looks like the inputted data for the personnel sometimes isn't saving, probably because there is no wait for one of them. I added a wait to the test case where data is inputted.

**Comment by thetif** [comment]
Chris, I'm getting some failing tests still. Can you look at it again, maybe try running `npm run cy:run` we want to make sure they pass that way because that's how the CI/CD will run it.

**Review by thetif — APPROVED** [review]
LGTM, all tests passing when I run them locally

**Pull request merged**
