### PR TITLE
fix cookie issue that preventing images from being fetched

### LINKED ISSUE #3180: [Bug] Images don't load unless you refresh page after logging in
**Description-**
Images are not loading if you have signed in without refreshing the page
**Type of Bug-**

- [ ] Accessibility
- [X] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**
Prerequisites: an APD with images.  This is trivial to create if you don't have one.
1. Log in as normal
2. (Optional)Open network console for tracking purposes
3. View an APD with images
4. See that images are displayed as broken
5. confirm 401 (unauthorized) status on image requests
6. confirm that image requests did NOT contain any value for the token (gov.cms.eapd.api-token)
7. refresh page
8. View an APD with images
9. confirm images are present
10. confirm images contain token value
11. logout and repeat

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [X] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
Images are shown on initial page load
**Actual results-**
Images are only shown if the page has been reloaded after login.
**Related user story/bug-** (if applicable)

**Additional information-** (optional)
I think this is caused by when the axios client is initialized and fed the token.  At the time it happens the token is not yet in scope because the user is logged out and then on a refresh the token is in scope and it happens as expected.
**Logs or error output/Screenshot/Video-** (at least 1 of these)
Available on request.

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

### PR DESCRIPTION
**Pull request by thetif**
resolves #3180

**Description-**
Resolves an issue with setting the cookie for viewing images.

**This pull request changes...**

- removes print statements from investigating the issue

**Steps to manually verify this change...**

1. login using em@il.com
2. open an APD
3. add an image to one of the rich text fields
4. make sure that the image displays
5. go back to the dashboard
6. open the same APD again
7. make sure that the image is still there

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] Changelog is updated as appropriate

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]

**Comment by chris-miraflor** [comment]
This pull request was manually verified:

1. Logged in using em@il.com
2. Opened an APD
3. Added an image to a rich text field on the APD Overview section and confirmed that the image loaded
4. Exited to dashboard
5. Opened the APD again
6. Confirmed that the image still loaded



Another test was done where I added different image to the rich text field of an APD's activities page, logged out and logged back in, then opened the APD again. The image still loaded. The added images also load after clearing browser cookies and cache.

**Review by jeromeleecms — APPROVED** [review]
Seems to work as advertised. Also saw the image from Darren so it seems to persist also after logging out and going to different parts of the app.

**Comment by akuas** [comment]
I was able to add a photo into the rich text editor and return back to it later.

**Review by akuas — APPROVED** [review]
I was able to upload an image to the rich text editor and return later to see it with the cookie.

**Pull request merged**
