### PR TITLE
Dmirano/3545/3429 small radio and language changes

### LINKED ISSUE #3545: [Feature] Key State Personnel - make yes/no checkbox fields consistent
Based on Design Task #3487

**Description and related issues -**
Change the order of the yes and no radio fields so that Yes is first.

### Figma
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5383%3A34045

### This task is done when…
- [ ] change the order of Yes/No on Key State Personal
- [ ] no option is pre-selected for the user

### PR DESCRIPTION
**Pull request by mirano-darren**
Resolves #3545 and #3429 

**Description-**
This is a language change in the Executive Summary section and radio change in the Key State Personnel subform.

**This pull request changes...**

- changed text in .yaml file that housed the Executive Summary help text
- /web/src/containers/APDKeyPerson/APDKeyPersonForm.js and unit test files affected

**This pull request was tested in the follow ways…**

- cypress tests pass
- unit tests pass
- manually testing

**Steps to manually verify this change...**

1. Go to the Executive Summary page and verify the help text has been changed to:
   - "This Executive Summary is automatically generated from the short descriptions you provided throughout the APD and activities. It is structured in a way so your State Officer can quickly assess the APD when starting their review. When the APD is exported, the Executive Summary will appear at the beginning of the exported PDF."
 
2. Go to the APD Key Personnel subform and make sure that the ordering of the radio's have Yes as the first option, and there is no default option selected. Also make sure the radio saves when trying to edit the form again.

### This pull request is ready to review when...

- [X] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [X] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [X] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Code looks good 👍

**Review by jeromeleecms — APPROVED** [review]
Great! Verified keyboard navigation and text changes.

**Review by thetif — APPROVED** [review]
good work

**Review by aricka-lewis — APPROVED** [review]
Looks great!

**Pull request merged**
