### PR TITLE
Knollfear/3264 use affiliation endpoint not jwt

### LINKED ISSUE #3264: [Feature] Update the manage account and select state components to use /affiliations/me
**Description and related issues -**
Use the new endpoint /affiliations/me to get an up-to-date list of user affiliations on the state selector and manage account components instead of the jwt.

### This task is done when…

- [ ] update state selector component to use the /affiliations/me instead of the jwt
- [ ] update manage account component to use the /affiliations/me instead of the jwt
- [ ] remove affiliations and permissions from the jwt

### PR DESCRIPTION
**Pull request by knollfear**
resolves #3264

**Description-**

changes the manage account and select state to pull from a live endpoint instead of the JWT

**This pull request changes...**

- how the data is pulled in for manage account (request new states)
- how the data is pulled in for select state

**This pull request also touches…**

the whole auth model so any part of auth could be broken now. 

- possible side effects of this change
inability to access parts fo the system that were previously accessible.  
Distinction between read and edit users should be confirmed

**This pull request was tested in the follow ways…**

- Log in and select a state shoudl work
- manage account should work and show states that you requested recently
- state switcher should include states that were just requested

**Steps to manually verify this change...**

1. log in
2. go to state selection and pick a state
3. go to manage account and request an additional state
4. go back to manage account and see the new state loaded
5. go to switch state and see the new state listed.

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by thetif** [comment]
@knollfear I think we need to adjust this, we don't want to see this screen if there is only one state to choose from.

Screen Shot 2021-07-15 at 3 57 58 PM

**Review by thetif — APPROVED** [review]
LGTM

**Comment by thetif** [comment]
Issue adding affiliation on login:
1. Log in as norole
2. Add an affiliation
3. See the Thank You screen.
4. Click Ok

Expect: to be taken to the dashboard

Actual: nothing happens and console log has errors

Screen Shot 2021-07-20 at 1 46 56 PM

**Comment by thetif** [comment]
Tested by:

|Given|When|Then|Result|
|---|---|---|---|
|a user with no affiliations|logging in the first time|they are prompted to choose and affiliation|:white_check_mark: PASS|
|a user with one affiliation|logging in|is taken to the state dashboard|:white_check_mark: PASS|
|a user with one affiliation|requesting more affiliations|is taken back to the state dashboard|:white_check_mark: PASS|
|a user with newly requested affiliations|going to the manage account page|is shown all fo the affiliations they just requested|:white_check_mark: PASS|
|a user with newly requested affiliations|going to the switch states pages|is shown all of the affiliations they just requested|:white_check_mark: PASS|
|a user with new requested affiliations on the switch state page|trying to switch to a newly requested state|is taken to the newly requested state|:white_check_mark: PASS|
|a user with multiple affiliations logging in|selecting a state to view|is taken to that state dashboard|:white_check_mark: PASS|

**Review by jeromeleecms — APPROVED** [review]
Works as described.

**Pull request merged**
