### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by thetif**
Describe the pull request here, including any supplemental information needed to understand it.

### This pull request changes...

- expected change 1
- expected change 2

### This pull request is ready to merge when...

- [ ] Automated tests have been updated (and all tests are passing)
- [ ] Bugs have been created for any issues found by QA beyond minor fixes
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by jeromeleecms — APPROVED** [review]
This looks fine to me, but tagging in the rest of the leads + QA to sign off.

**Comment by beparticular** [comment]
@thetif there was something in a recent PR where @radavis described how to test something that wasn't straightforward. That was super helpful. I know we won't need that all the time, but would it be worth adding something like that to the template in the event it is needed or might be helpful?

**Comment by thetif** [comment]
good idea @beparticular

**Review by eStar386 — APPROVED** [review]

**Review by cthulhuplus — APPROVED** [review]
👍

**Comment by beparticular** [comment]
@thetif that's great - do you need anything else from me on this?

**Comment by thetif** [comment]
nope

**Pull request merged**
