### PR TITLE
Bbrooks/1503 splunk move pm2 logs

### PR DESCRIPTION
**Pull request by cthulhuplus**
In this PR:
I removed the splunk user being added to the ec2-user group, that did not work to grant Splunk access to /home/ec2-user. 
Added a path for the cms-hitech-apd-api.logs so that it is created in /app/api/logs/cms-hitech-apd-api.logs
Moved pm2 logs from /home/ec2-user/.pm2/logs directory to /app/api/logs
Updated CloudWatch to reflect the new log locations

### This pull request changes...

- splunk user can access /app/apli/logs
- splunk user can not access /home/ec2-user/
- CloudWatch pulls from new log locations

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Seems fine 👍

**Comment by radavis** [comment]
Thoughts I'm having while looking at this PR:

- How will this change affect local development? How about development with docker?
- Should we separate error and output logs? Would this make tracking down 'cause and effect' more difficult? Or, is this concern mitigated by Splunk?

I'll set aside some time today to look into the first question.

**Comment by cthulhuplus** [comment]
@radavis The Splunk agent merely reads and forwards the local logs. Other than changing the locations of the logs, they should remain completely intact the way that we have them now.

**Comment by cthulhuplus** [comment]
New log(s) is showing in CloudWatch:
image

**Review by thetif — APPROVED** [review]

**Comment by cthulhuplus** [comment]
After speaking with Richard I have added a new log group that combines the output and error logs into one.

**Comment by cthulhuplus** [comment]
image

**Pull request merged**
