### PR TITLE
added help text to Contract Term field

### PR DESCRIPTION
**Pull request by thetif**
Added help text to Contract Term and Total Contract Cost 

### This pull request changes...

- updated text under Contract Term
- updated text under Total Contract Cost

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
~- [ ] The change has been documented~
~- [ ] Associated OpenAPI documentation has been updated~
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by beparticular** [comment]
@thetif typo in the help text "Contract term my extend beyond the FFY(s) included in this APD."
my = may

**Comment by thetif** [comment]
oops @beparticular fixed

**Review by beparticular — APPROVED** [review]

**Review by radavis — APPROVED** [review]
Looks good from here 👍

**Review by jeromeleecms — APPROVED** [review]
Looks good!

**Pull request merged**
