### PR TITLE
Tbolt/2830 checks for error before displaying Saved! message in header

### LINKED ISSUE #2830: [Dev] Fix issue when saving via the "Unable to save" message showing "Saved" when it's actually failing to save
Bug Found in #2848 
In my testing I was able to force the "Unable to save" message by shutting down the backend. Then when clicking the "Save" button provided by that alert message, it would spin for a minute and then say "Saved." However, this is not actually saving and there is an error thrown in the console (plus the backend is turned off)

Bug - 
Notice in this screenshot the error connection refused and the SAVE_APD action failed. Yet the UI shows it was successfully saved. 

### This task is done when…
 - [ ] The UI reflects the state of the system accurately

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2830 

### This pull request changes...

- When there is an error saving the page, it will no longer show the "Saved!" message in the header. Instead it will use "Last saved" time.

### Testing guidance
1. First login to staging and verify current behavior by completing steps 3-6. You should see that even when Offline it is showing a "Saved!" message in the header.
2. Login to PR environment
3. Create/view APD
4. Make some changes
5. Use dev tools to set the network to Offline
6. Make more edits
7. Header should **not** say "Saved!" instead it should display the last saved time

### This pull request is ready to merge when...

- [x] Develop has updated automated tests (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] QA has manually tested and created bugs for any issues found (beyond minor fixes)
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good

**Comment by eStar386** [comment]
Future Parking Lot:  Offline users still receive the saving icon then it goes to the last saved message. As such, the user isn't notified they are still offline. It is noted Jerome stated it isn't a high priority fix and it does display the last known save message now. @NAretakis @tbolt @beparticular

**Review by eStar386 — APPROVED** [review]
Passes Functionality and Accessibility - stops the user from inputting data when the connection is lost via a persistent modal.

**Review by beparticular — APPROVED** [review]

**Review by NAretakis — APPROVED** [review]
Good to go.

**Pull request merged**
