### PR TITLE
Updates email address in footer

### LINKED ISSUE #2353: Email address listed in the footer of the app is incorrect
The email address in the footer of the application points to CMS-EAPD@cms.gov; instead it should point to CMS-EAPD@cms.hhs.gov

### This task is done when...
 - [ ] Email address has been corrected
 - [ ] Email address mailto: link has been corrected
- [ ] Product has signed off on the change

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2353 

### This pull request changes...

- Updates email address in footer

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Review by beparticular — APPROVED** [review]

**Comment by beparticular** [comment]
@tbolt at the bottom of the export view, there is a return to the top of the page link. can you see what that is saying is the "top of the page"? bc when I click on it, it takes me to the top of the blue box, and the link back to APD still appears to be missing. thx!

**Review by jeromeleecms — APPROVED** [review]
Looks great.

**Comment by tbolt** [comment]
@beparticular those issues are solved (at least attempted to be solved) in another story/PR

**Comment by beparticular** [comment]
@tbolt ah! I knew I left this comment somewhere, but couldn't find it here clearly on the wrong issue. thanks for the heads up.

**Pull request merged**
