### PR TITLE
Tbolt/3676 Admin Check

### LINKED ISSUE #3544: [Feature] Create the animation for error check
The animation should exist so it's clear the error check is done. 
This happens when all the fields are complete and is shown in the help drawer. 
Consider 508 compliance, an announcement when the check is complete. 

Figma Link
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2021?node-id=5533%3A38088

### This task is done when…

This could include:

- [ ] the animation is created 
- [ ] the animation is approved by product  
- [ ] identify 508 considerations and/or recommendations
- [ ] any tangible deliverable(s) that need to be created

### LINKED ISSUE #3675: [Feature] Ability to toggle Admin Check errors in the APD
**Description and related issues -**
Add a button to the export and submit page that turns on the Admin Check and display the help drawer to the users.

**Mockups or link to Figma**

### This task is done when…

- [ ] clicking the Run Administrative Check turns on the display error toggle

### LINKED ISSUE #3676: [Feature] Create help drawer to display output from the Admin Check
**Description and related issues -**
Create a help drawer component that will be fixed to the top right of the page and can be expanded to see more details. This help drawer should only be visible if the user has the Admin Check turned on. This should display the data collected in #3674 and #3675. 

The Continue to next section will be an active button, so they can continue to the next section that has errors even if they are not done with the page that they are on. Once they get to the last page that has errors, the admin check will just loop back to the first page that still has errors, if they had skipped any, or it will display that there are no more errors.

**What is the goal or purpose of this ticket?**

**Mockups or link to Figma**
If there are errors

if there are no errors

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
| Admin Check is off | any time | the help drawer is not visible |
| Admin Check is on | the users is on a page with errors | the help drawer gives a detailed list of errors for that page |
| Admin check is on and the user is on a page with errors | the user resolves one of the errors | the help drawer updates to remove that error from the details |
| Admin Check is on | the users clicks the Continue to the next section button | they are taken to the next section of the APD with errors |
| Admin check is on and the user is on the last page of the APD with errors and there are still errors on previous pages | the user click the Continue to the next section button | they are taken to the first section in the APD with errors |
| Admin check is on | the users resolves all of the errors | the help drawer updates to show the no errors view |

### This task is done when…

This could include:

- [ ] all acceptance criteria are met
- [ ] identify 508 considerations and/or recommendations

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #3676 
Resolves #3675 
Resolves #3544

### Description

Adds initial react components for the admin check panel. Some additional notes-
* The data is mocked and not real. Everything in the “collapsed” is hardcoded HTML.
* Still need to come up with semantics for the custom parts of the panel. (Ie. What is the Incomplete Required Fields? A heading? How is the # tied to it?)

### Signifcant changes or possible side effects
* There shouldn't be any impact to existing functionality or new side effects introduced

### Automated test cases written
* Some test cases were created to test the basic pieces around the panel:
  * Opening and closing
  * Showing the completed state
  * Collapsing/Expanding the mini check
* More testing will be completed in subsequent stories
* Cypress tests are going to be a separate ticket

### Steps to manually verify this change

1. Login as a user who can view/edit APDs
2. Navigate to to APD export and submit page and click Run Administrative Check
3. Verify Admin Panel appears and matches criteria in original ticket

### This pull request is ready to review when

- [x] Automated tests are updated (and all tests are passing)
- [x] Pull request has been labeled, if applicable with feature, content, bug, tests, refactor
- [x] Associated OpenAPI documentation has been updated
- [x] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when

- [x] Code has been reviewed by someone other than the original author
- [x] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
great work

**Review by Sun-Mountain — APPROVED** [review]
⭐

**Comment by mirano-darren** [comment]
Looking good so far! 
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| admin check panel  | admin check is complete (used demo button to mark as complete)  | complete animation is played  | PASS ✔️ |
| Export and Submit page  | admin check get turned on  | admin check help panel appears  | PASS ✔️|
| admin check help panel  | the user turns off the admin check via the  panel  | admin check help panel disappears  | PASS ✔️|
| admin check help panel  | admin check is complete and turned closed  | help panel disappears  | PASS ✔️|
| admin check help panel  | testing out various buttons, accordions, direct links  | all work as intended, some issues are already noted in the PR  | PASS ✔️|

Since this is a WIP I'm sure you know about this. But just to make sure, these links/buttons don't redirect me: 
image
image

**Comment by mirano-darren** [comment]
@jeromeleecms @beparticular Ready for your review! Keep in mind that most of the data in the panel is all hardcoded (not synced up with the APD yet)

**Comment by tbolt** [comment]
@jeromeleecms @beparticular here are the notes from our experiment session-
* Ty to push up change where layout is left-aligned to see if we can use that margin to allow more space for admin check panel. Noting that some sections (such as the landing page/dashboard) may look weird. 
* Jenn proposed Incomplete field # to be consistent between the admin check and mini check(calling the "collapsed view" the mini check 😄). currently its in a rounded rectangle in the regular check and oval in mini check
* Recently Completed could be removed and revisited when we have a better sense of how and why this is needed
* Remove the accordion headers highlight
* Jenn noted this might be a good opportunity for a quick usability test

**Comment by jeromeleecms** [comment]
@tbolt 

Did you ever figure out why it's doing this?

image

Also, did you ever figure out why the link only works once? Or are you waiting to fix that when you do a full implementation of the admin check?

**Comment by tbolt** [comment]
@jeromeleecms Need to look into both of those issues. I thought the link issue was resolved but im seeing it not working for certain links.

**Review by thetif — APPROVED** [review]

**Comment by mirano-darren** [comment]
Looks good to me! Tested functionality of frontend components. Note: direct link is broken when coming from an activity, Ty has already acknowledged this. 
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| Admin check is turned on/off  | Looking throughout the builder | Inline validation is turned on/off based on admin check  | PASS ✅ |
| Admin check help panel | Admin check is complete (toggled w/ demo button)  | Animation plays and collapse button changes to close  | PASS ✅ |
| Admin check is on | User returns to the APD dashboard | Admin check is turned off when entering back into the APD  | PASS ✅ |
| Admin check help panel |  Navigating to other pages via direct link or edit button  | User gets redirected to the correct page | PASS ✅, broken links coming from activities already noted |
| Admin check help panel | user clicks Stop Administrative Check button | Help panel closes and inline validation turns off on page reload | PASS ✅ |

**Review by thetif — APPROVED** [review]

**Review by thetif — APPROVED** [review]
great work! I love the clean up too

**Review by mirano-darren — APPROVED** [review]
Looks good to me! Well done Ty! 
Ready for your review @jeromeleecms @akuas (Would also tag Sherry here, but she isn't in this repo?)

Note: Date validation issues are addressed in #4366

**Comment by jeromeleecms** [comment]
@mirano-darren I added Sherry.. also, it says a test is failing, is this ready for review or does the owasp zap scan need to resolved first?

**Comment by tbolt** [comment]
@jeromeleecms I had pushed up code that was intended for another branch which may have broken the build. Looks good now though.

**Comment by jeromeleecms** [comment]
@tbolt Remind me - for the assurances and compliance section, the help text is "select yes or no" -- did we decide to leave it vague like this or can we incorporate which assurance and compliance wasn't answered? (similarly for "Please Explain" section if people say no)

Example: "Are you complying with 42 CFR 495.360? Select Yes or No."

It seems like this section is based on the validation text, so if we have to spin up a separate ticket for targeted improvement, I'm also good with that path...

Otherwise looking very good.

**Review by jeromeleecms — APPROVED** [review]
Works as advertised with the known exceptions.

**Review by akuas — APPROVED** [review]
Works as expected!

**Comment by SGilliamA1M** [comment]
Looks good and works as expected.

**Pull request merged**
