### PR TITLE
added endpoint for pulling a user's own affiliations.=

### LINKED ISSUE #3207: [Feature] Create an endpoint to get a user's existing affiliations
**Description and related issues -**
The Manage Account page needs to see all of a users current affiliations to fill out the Existing Affiliations section. Create an endpoint that will return the user's affiliations with their state and status.

**Mockups or link to Figma**
https://www.figma.com/file/6eVvo7JjvXiovGTR4BoVgK/CMS-eAPD-2020?node-id=3771%3A146

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
| a user id | the user has affiliations | it returns the user's affiliations |
| a user id | the user has not affiliations | it turns an empty array |

### This task is done when…

This could include:

- [ ] there is a new endpoint
- [ ] all acceptance criteria are met

### PR DESCRIPTION
**Pull request by knollfear**
a user must be logged in, but requires no specific permissions for this endpoint.

resolves #3207

**Description-**

Creates /affiliations/me endpoint that delivers an array of all the current user's affiliations.
**This pull request changes...**

- /affiliations/me endpoint
- updates open api docs

**This pull request also touches…**

- possible side effects of this change
none, this is an isolated endpoint sharing almost no code with other functions.
**This pull request was tested in the follow ways…**

- l just set up a postman call to verify it

**Steps to manually verify this change...**

1. log in and capture your current token
2. use that token in postman to hit this endpoint and verify results
3. request a state via the website
4. rerun postman to ensure your new state is added
5. drop a state in the db directly
6. rerun postman and make sure state is gone 

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Comment by thetif** [comment]
Looks good except for, possible issue with the returns not having all of the data filled out. I'm not sure if that's expected or if it's a side effect from this bug that I logged earlier. #3242

Tested by:

|Given|When|Then|Result|
|---|---|---|---|
|logged in as norole|requested "co, md, ca, and ak"|hit the new endpoint and it returned all of them|PASS|
|logged in as norole|requested "tx"|hit the endpoint and it return all of the above|PASS|
|logged in as norole|hit new endpoint|all of the requested states were returned and they were all marked as requested|PASS|
|logged in as fedadmin and approved norole for AK|logged back in as norole|hit the endpoint and it returned all of the affiliations and now ak was approved|PASS|
|logged in a norole|hit new endpoint|results did not have values for the following fields: "displayName, secondEmail, primaryPhone, mobilePhone"|FAIL|

**Comment by thetif** [comment]
That last failure will be fixed in #3242

**Review by jeromeleecms — COMMENTED** [review]
How often is this updated when pulling your affiliations? I added a state affiliation, submitted it, and then came back to the manage account page. The new state I requested doesn't show up unless I refresh the page manually in the browser.

It seems like if it's asked, the endpoint provides the right affiliations (so this seems to be working), but it the system doesn't know WHEN to ask...

**Comment by knollfear** [comment]
> How often is this updated when pulling your affiliations? I added a state affiliation, submitted it, and then came back to the manage account page. The new state I requested doesn't show up unless I refresh the page manually in the browser.
> 
> It seems like if it's asked, the endpoint provides the right affiliations (so this seems to be working), but it the system doesn't know WHEN to ask...

What you are describing is actually a slightly different issue.  The state switcher pulls the list of affiliations from the JWT, which is only issued on login.  As a result the state affiliations page is not being updated effectively.  However, we are aware of this and will fix it after launch.  In addition, this ticket just creates an endpoint for pulling the data, it doesn't actually wire it in anywhere to the front end.  We are working towards the figma model, but we are not there yet, this is just one step in that direction.

**Review by jeromeleecms — APPROVED** [review]
Sounds good @knollfear.

**Pull request merged**
