### PR TITLE
Tbolt/2370 hr inconsistencies

### LINKED ISSUE #2370: Dividing lines inconsistently presented across pages
Some pages show a double line or no line at all in the header section. All pages should have a single dividing line.

### This task is done when...
 - [ ] All pages show only one dividing line in the header section.

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2370

### This pull request changes...

- Updates sections to only have one horizontal rule (divider lines)

### This pull request is ready to merge when...

- [x] Tests have been updated (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [x] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [x] Changelog is updated as appropriate

### This feature is done when...

- [x] QA has approved the experience
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by jeromeleecms** [comment]
@eStar386 If this passes all your other QA tests, I'll do the final accessibility review as part of my final sign off after you pass it along to me and Jenn.

**Comment by eStar386** [comment]
QA Passed - on the removal of the double headings. However, it is still inconsistent with use of the single line headers. Below I have specified all the ones without single line within in the header.
Roles Tested: personal user, statestaff, statecontactor, stateadmin, em@il

Test Steps: 
1. From the left nav bar, select each menu Item
Executed Results: No double headers.

Note: Inconsistent use of single headers: Some of the headers have a single line and others have no line. 

Steps to Reproduce Issue: Using the test steps above,  APD overview, Export and Submit, Add Activity are without the single line. All other first subheadings or in the case of Activity Schedule Summary have the single line present.

**Review by eStar386 — APPROVED** [review]

**Review by eStar386 — APPROVED** [review]

**Comment by beparticular** [comment]
@tbolt noted they will fix, in this issue, the inconsistencies that @eStar386 pointed out. Let me know when it's ready to review again.

**Review by thetif — APPROVED** [review]
Looks good

**Comment by tbolt** [comment]
@eStar386 Requested changes have been made. Take a look at let me know if there are any issues

**Comment by eStar386** [comment]
Still inconsistent with activity vs previous activities.  Please view screenshot 
1. Most pages with help text ex. 
previousActivities
2.Activities 
activityhelptext

**Review by eStar386 — APPROVED** [review]

**Comment by tbolt** [comment]
@eStar386 I went ahead and added the missing dividing line there. I'll let @beparticular and @akuas be the final say in how the lines are now.

**Review by jeromeleecms — APPROVED** [review]
This changes look good to me. If the page has help text to get started, it seems like you wrapped it between two <hr>, if no help text appears (or is tied to a lower section), a single <hr> is used. Screen reader doesn't pick up the lines and it just reads through the content as expected.

**Review by beparticular — APPROVED** [review]

**Pull request merged**
