### PR TITLE
fixed issue with second response once headers have already been sent

### LINKED ISSUE #3283: [Bug] CloudWatch Errors
**Description-**
While in CloudWatch I discovered these two entries in the eAPD-API-error-0.log log. 

```
2021-07-15T09:17:15.013-04:00
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
```

```
2021-07-15T09:17:19.018-04:00
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:561:11)
    at ServerResponse.header (/app/api/node_modules/express/lib/response.js:771:10)
    at ServerResponse.json (/app/api/node_modules/express/lib/response.js:264:10)
    at ServerResponse.send (/app/api/node_modules/express/lib/response.js:158:21)
    at /app/api/routes/me/get.js:41:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [ ] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Log into AWS CloudWatch
2. LogGroups > Prod > eAPD-API-error-0.log
3. Go to the time stamps

Don't know what triggered these unfortunately

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Expected results-**

**Actual results-**

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

---

Add additional labels (design, dev, compliance, BUG, etc) and size before submitting.

If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for prioritization in backlog refinement or sprint planning with Product.

### PR DESCRIPTION
**Pull request by thetif**
resolves #3283 

**Description-**
Fixes some error handling in the /me and /me/jwToken endpoint to prevent an error where the response headers are sent twice.

**This pull request changes...**

- updated returns and error handling for /me and /me/jwToken endpoints

**Steps to manually verify this change...**

1. using postman send an invalid jwt to the /me endpoint
2. you should get an invalid token error
3. using postman send an invalid jwt to the /me/jwToken endpoint
4. you should get a 401 error
5. using the browser login with a valid user and password
6. you should be able to login normally

### This pull request is ready to review when...

- [X] Automated tests are updated (and all tests are passing)
- [X] Changelog is updated as appropriate

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by knollfear — APPROVED** [review]
works locally as expected and code looks solid.

**Comment by knollfear** [comment]
Tested on deployed version and got these results:

| Given | When | Then | Result |
|---|---|---|---|
| the JWT token is invalid | Postman makes a request to /me | the response has status 401 and an error body | :white_check_mark: PASS |
| the JWT token is invalid (this is the okta JWT) | Postman makes a request to /me/jwToken | The response has status 401 and no error body | :white_check_mark: PASS |
| the JWT token is valid | Postman makes a request to /me | the response has status 200 and the expected body | :white_check_mark: PASS |
| the JWT token is valid (this is the okta JWT) | Postman makes a request to /me/jwToken | The response has status 200 and the expected body | :white_check_mark: PASS |

**Comment by tbolt** [comment]
This looks good and works as described. 

Testing results with local build
| Given | When | Then | Result |
| ----- | ----- | ----- | ----- |
| the JWT token is invalid | making a request to /me | the response is an invalid token error | ✅Pass |
| the JWT token is invalid | making a request to /me/jwToken | the response is a 401 | ✅Pass |
| the JWT token is valid | making a request to /me | the response is 200 with response body | ✅Pass |
| a valid user account (State Admin test account used) | logging in to the app | login process works as normal | ✅Pass |

**Review by tbolt — APPROVED** [review]
Added testing results in another comment.

**Review by jeromeleecms — APPROVED** [review]
Dev team has approved this. Good to go.

**Pull request merged**
