### PR TITLE
Removed extraneous instances of 'another' from button text

### LINKED ISSUE #3009: [Dev] Remove the word "another" from all buttons
created from design task #2366

Remove the word "another" from all buttons, another isn't always true, and it's extraneous wording in small buttons.

Pages with another in the button
Key State Personnel -> Add Key Personnel
On Activities homepage -> add another activity

Within the actual activity aka Activities
Outcomes and milestones -> add another outcome / add another milestone
State staff and state expenses -> add another state staff/state expense
Private contractor costs -> add another contractor
Budget and FFP -> add another activity

### This task is done when…
 - [x] the button is labeled Add Key Personnel
 - [x] the button is labeled Add Activity
 - [x] the button is labeled Add Outcome
 - [x] the button is labeled Add Milestone
 - [x] the button is labeled Add State Staff
 - [x] the button is labeled Add State Expense
 - [x] the button is labeled Add Contractor
 - [x] the button is labeled Add Activity

### PR DESCRIPTION
**Pull request by chris-miraflor**
resolves #3009 

**Description-**
Removes the word 'additional' from button label text from buttons in the key personnel and activities pages when editing an APD.

**This pull request changes...**

- Removes the word 'another' from button label text in:
  - Activities dashboard
  - Pages for editing activities
    - Outcomes and milestones
    - State staff and expenses
    - Private contractor costs
    - Budget and FFP

**This pull request also touches…**

- May affect tests done for the activities/key personnel pages if tests look for specific text for the buttons

**This pull request was tested in the follow ways…**

- Going to the pages containing the button with edited text and verifying that the word 'another' is no longer present

**Steps to manually verify this change...**

1. Log in and access APD
2. Navigate to the activities dashboard
3. Confirm that button says 'Add activity' instead of 'Add another activity'
3. Edit an existing activity or create a new activity and edit the new activity
4. Confirm that none of the buttons in the pages for editing the activity have 'additional' in their label
5. Navigate to key personnel page
6. Confirm that none of the buttons have 'additional' in their label

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [X] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [X] QA has verified the accessibility and functionality related to the change
- [X] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks good!

**Review by tbolt — APPROVED** [review]
Nice work!

**Comment by thetif** [comment]
Looks good. Test by looking at all of the buttons listed in the ticket and confirming that they have been updated.

**Review by beparticular — APPROVED** [review]

**Review by jeromeleecms — CHANGES_REQUESTED** [review]
Per the issue, all the button content should be titled cased - please update.

**Review by jeromeleecms — APPROVED** [review]
Thanks @chris-miraflor - updates match the changes listed in the issue now. Nice work.

**Pull request merged**
