### PR TITLE
Knollfear/2962 state admin table

### PR DESCRIPTION
**Pull request by knollfear**
This adds a table for state_admin_certifications and seeds it with some data.  The table exists but isn't  exposed to or used by the API yet.

### This pull request changes...

- Adds a table called 'state_admin_certifications' and 'state_admin_certifications_audit'
- seeds data into both tables
### This is how to verify this change...

with the containers running execute the following commands:
`
docker-compose exec api npm run migrate
`
then
`
docker-compose exec api npm run seed
`
finally connect to the DB and verify that the values exist with these queries:

`
select * from state_admin_certifications_audit;
`
and

`
select * from state_admin_certifications;
`
### This pull request is ready to merge when...

- [x] Develop has updated automated tests (and all tests are passing)
- [x] This code has been reviewed by someone other than the original author
- [x] QA has manually tested and created bugs for any issues found (beyond minor fixes)
~~- [ ]The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~~
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [x] QA has verified the accessibility and functionality related to the change
~~Design has approved the experience~~
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — CHANGES_REQUESTED** [review]
@knollfear all of these updates are made in 2947 so they should be merged into main soon

**Review by thetif — APPROVED** [review]
thanks

**Review by eStar386 — APPROVED** [review]
Passes -  Validated the table exists with correct columns +  accepts data.  
Document Exemption: Accessibility Testing is N/A.

**Review by NAretakis — APPROVED** [review]
Good to go.

**Pull request merged**
