### PR TITLE
Dio/4008 create validation

### PR DESCRIPTION
**Pull request by itsonlydio**
Resolves #

Create validation tests to make sure that the Packer code written is valid and remains valid.
Files we're validating:
backend-ami.pkr.hcl
mongo-ami.pkr.hcl
preview-ami.pkr.hcl

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |

### Steps to manually verify this change

1.
2.
3.

### This pull request is ready to code review when

- [ ] Automated tests are updated (and all tests are passing)
- [ ] New automated test cases are documented above
- [ ] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by cthulhuplus — CHANGES_REQUESTED** [review]
Please remove dio-tests.js since it is an empty file.

**Comment by itsonlydio** [comment]
removed dio-tests.js

**Review by cthulhuplus — CHANGES_REQUESTED** [review]
Could clean up some of the excess spacing like lines 3-5, 24 & 25, 38-40, and 401-403?

**Review by thetif — APPROVED** [review]
looks good

**Review by cthulhuplus — APPROVED** [review]
LGTM

**Pull request merged**
