### PR TITLE
Tbolt/2583 state admin dashboard

### LINKED ISSUE #2583: State Admin dashboard
Create a state admin dashboard where the admins can see requests for access for their state and the status of their current and previous state users. Allow admin to view/approve/deny/revoke user access for their state.

### This task is done when...
 - [ ] the State Admin dashboard is created
 - [ ] the admin can select a user to view and manage
 - [ ] the admin can revoke a user's access to their state
 - [ ] the admin can approve a user's access request
 - [ ] the admin can reject a user's access request
 
*Add a LABEL (design, dev, compliance, BUG, etc) before submitting.

*If the issue is needed to complete prioritized work for the CURRENT SPRINT, add it to the "This Sprint" pipeline. Otherwise, all other issues will be automatically added to the _unprioritized pipeline_ for PRODUCT to prioritize.

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2583 

### This pull request changes...

- Adds the state admin dashboard

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by beparticular — APPROVED** [review]
Ty and I walked through this and it looks great. 
Since I'm heading out at 4pm today I'm approving pending the question of if "federal admin" will show in the roles area and the language on the empty state changed to something like "No users on this tab at this time". Hooray!

**Review by jeromeleecms — COMMENTED** [review]
Here's a little wierdness:
1) Click on Requests - Shows the new account:

image

2) Click on Active - Show's the pending account (is this the right behavior?)

image

3) Click on Inactive (looks right at this point)

image

4) Click back to active - but now it's empty:

image

What should I be expecting to see in this active tab?

**Review by thetif — APPROVED** [review]

**Comment by jeromeleecms** [comment]
**Approving A User** - as before, saw the pending account, 

- clicked "Approve", selected the role and clicked "Save." 
- Account still shows as a request (instead of disappearing - is that the right behavior)? 
- Clicking on "Active" still shows the  previous behavior as the previous comment (pending account shows up)
- Clicking on "Edit Role" in the active tab, allows me to also select role and "Save" or "Cancel," but it doesn't update the account, so it still shows in "Requests"
- Clicking on "inactive," back to "active" causes the "active" tab to be empty (as previously noted)

**Revoking A User** - this works, after denying access, the pending account disappears from the "Requests" tab and moves to the inactive tab. Denied status shows properly:

image

**Trying to Restore Access** - this does **not** work, but probably due to the same issue as not being able to save users when granting them initial access(?)

**Review by jeromeleecms — COMMENTED** [review]
Looks good.

**Pull request merged**
