### PR TITLE
Tbolt/2743 fte help text

### LINKED ISSUE #2743: [Dev] Help text around FTE number or percent is confusing or unclear
Dev task for #2730
screenshot

Update FTE Allocation help text in Key Personnel 

### This task is done when…
 - [ ] removed 1 = 1 FTE or 100% time on both FTE Allocation field labels
 - [ ] added "For example 0.5 = 0.5 FTE - 50% time" in the same pattern we use for the start/end date example

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2743 

### This pull request changes...

- Updates FTE form help text to proposed design

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by beparticular — CHANGES_REQUESTED** [review]
I seem to have left off the : after For example in my mock up
Correct is "For example:" 
Is the general pattern we use for help text. Sorry about that.

**Review by jeromeleecms — CHANGES_REQUESTED** [review]
@tbolt let's add the colon after "For Example:" - pattern from the Contract Term page:

image

**Comment by jeromeleecms** [comment]
Sorry didn't mean to double dip on that colon issue! Didn't see @beparticular comment while I was reviewing.

**Comment by tbolt** [comment]
@jeromeleecms @beparticular I was wondering about the colon, but that's why we do review 😄 It's there now. Thanks

**Review by beparticular — APPROVED** [review]

**Review by jeromeleecms — APPROVED** [review]
Thanks @tbolt. Gtg from me.

**Review by thetif — APPROVED** [review]

**Pull request merged**
