### PR TITLE
Tbolt/3707 Remove cancel button on state affiliation switch page

### LINKED ISSUE #3707: [Bug] Unclickable login button after clicking "Cancel" upon stateadmin login
**Description-**
After logging in as stateadmin, choosing the cancel option on the state select screen results going back to the login screen. The login button is stuck on "Logging in" and becomes unclickable. 

I believe I found this during my internship, but I looked through the current bugs and couldn't find this issue. Apologies if this matter has already been discussed.  
**Type of Bug-**

- [ ] Accessibility
- [ ] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

1. Login as stateadmin
2. On the state selection page, click cancel
3. Verify you are sent back to the login page with the login button turned into "Logging in"

**Role Affected-**

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [ ] All
- [ ] PR #\_\_\_\_
- [X] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
When sent back to the login page, the login button should be clickable
**Actual results-**
The login button turns into an unclickable "Logging in"

**Additional information-** (optional)
Refreshing the page acts as if the default state was chosen, and brings you to that state's dashboard. 

Is a cancel button necessary on the state selection screen? A simple solution could be not giving the option to cancel the state selection during the login process. 
**Logs or error output/Screenshot/Video-** (at least 1 of these)

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #3707 

**Description-**

**This pull request changes...**

- Updates the state affiliation switch page to no longer have a cancel button

**Steps to manually verify this change...**

1. Login with a user that has multiple state affiliations
2. Verify that the state selection page/component no longer displays the cancel button
3. Verify "Submit" still works as expected

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by mirano-darren — APPROVED** [review]
Looks good, cancel button is gone and thus cannot reproduce bug. Nice work!

**Review by thetif — APPROVED** [review]
LGTM 👍

**Review by Sun-Mountain — APPROVED** [review]
Test results

|Given|When|Then|Result|
|---|---|---|---|
|Cancel button| on state selection page that has multiple state affiliations|is no longer displayed|:white_check_mark: PASS|
|Submit on State Selection|when selected|still works as expected|:white_check_mark: PASS|

**Review by aricka-lewis — APPROVED** [review]
Looks good!

**Review by jeromeleecms — APPROVED** [review]
Looks good!

**Pull request merged**
