### PR TITLE
audit table for logging in

### LINKED ISSUE #3427: [Feature] Create user audit tables
**Description and related issues -**
We are currently tracking anonymized users with google analytics, but we should also be recording user logins in our database.

### This task is done when…

- [ ] create an okta_user_audit table
- [ ] record successful login attempts to the table

### PR DESCRIPTION
**Pull request by thetif**
Resolves #3427 

**Description-**
Adds an audit table for storing user logins. 

**This pull request changes...**

- the jwt creation step to log when a user accesses a state

**This pull request also touches…**
- changing states and expiring affiliations

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
looks good 👍

**Review by mirano-darren — CHANGES_REQUESTED** [review]
test

**Review by mirano-darren — APPROVED** [review]
looks good!

**Review by jeromeleecms — APPROVED** [review]
Content and structure seem fine. We'll need to spin up a different ticket to visualize the content of the databases/tables.

**Comment by thetif** [comment]
Here is what the audit table looks like

**Pull request merged**
