### PR TITLE
Tbolt/4182 Fix issue with renewing state admin

### LINKED ISSUE #4182: [Bug] Fix issue with renewing State Admin
### Description
When trying to renew a state admin, the automated matching doesn't work.

### Steps to reproduce

1. Approve a state admin for current FFY
2. Upload new letter for next FFY

**Expected results-**
The automated matcher should pick up that the existing person is connected to the letter.

**Actual results-**
The person is ignored because they already have a match (for the current FFY)

### Role Affected

- [ ] All
- [ ] Federal Admin
- [X] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

### Environment

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

### Browser

- [X] All
- [ ] Firefox
- [ ] Chrome
- [ ] IE

**Cypress test created OR Ticket for cypress test created-**

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4182 

### Description
Updates the state admin matching process to allow matching on already existing matches.

### Significant changes or possible side effects
State admins who have been previously approved should now be eligible "matches." Unsure if any side effects are introduced from this.

### Automated test cases written
Test added to verify that state admin role will return a match

### Steps to manually verify this change
1. Login as fed admin
2. For a already valid state admin user for this current FFY, add a new certification for next FFY
3. Verify that the certification has a match
4. Verify that you can make the match successfully

### This pull request is ready to review when

- [ ] Automated tests are updated (and all tests are passing)
- [ ] Pull request has been labeled, if applicable with feature, content, bug, tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when

- [x] Code has been reviewed by someone other than the original author
- [x] QA has verified the functionality related to the change
- [x] QA has verified the accesibility using tools such as screen readers and WAVE (accessibility evaluation tool)
- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]

**Comment by mirano-darren** [comment]
Looks good to me!
| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| Fed admin panel  | Testing in main (not this PR)  | Approving State Admin, then re-adding the same user for 2023  | Cannot find a match for the 2023 user; expected bug behavior  |
| Fed admin panel  | Testing in this PR| Approving State Admin, then re-adding the same user for 2023  | Able to find find a match despite the user already approved. PASS ✅ |

**Review by mirano-darren — APPROVED** [review]

**Review by akuas — APPROVED** [review]
Works as expected. Maybe this is obvious, but a consideration is that the record a (FFY 2022) must be matched before adding a new certification for record b (FFY 2023). If you don't it will just list both without the ability the match record b. I don't see this as a bug and I wasn't able to identify any real issues with the way it work now.

**Comment by akuas** [comment]
Just to clarify, as a user you just need to make sure that the status of the previous user says matched before you recertify, but it is a nonissue.

**Review by jeromeleecms — APPROVED** [review]
This works as advertised. Thank you.

**Pull request merged**
