### PR TITLE
Tbolt/2744 previous activities table headings

### LINKED ISSUE #2744: [Dev] Results of Previous Activities Actual Expenditure Table has confusing headings
Dev task for #2723 

Update Results of Previous Activities tables

screenshot

### This task is done when…
 - [ ] removed the first header from all of the tables
 - [ ] update the headers from all of the tables to match the screenshots
 - [ ] change label under Actual Expenditures to "Provide the most recently approved Total Computable Medicaid funding and the actual FFP expenditures. The application will calculate the approved FFP based on the listed match rate."

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #2744 

### This pull request changes...

- Updates Previous Activities table headings to match proposed design

### This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by beparticular — APPROVED** [review]
This looks great, very satisfying. @jeromeleecms does this improve the navigation on screenreaders to have removed one of the headers?

**Comment by jeromeleecms** [comment]
@tbolt Can we align the columns with what the screen reader is reading? 

For example, the screen reader is currently reads the aria-label: "total approved funding for HIT and HIE for FFY 2017, state plus federal. Enter amount in dollars." for the first column, which doesn't line up with the column header: "Approved total computable Medicaid funding for HIT and HIE for FFY 2017. Enter amount in dollars."

The other form field has this aria-label: "actual federal share for HIT and HIE for FFY 2017. Enter amount in dollars." it should align with the new column header "actual ffp expenditures for HIT and HIE for FFY 2017. Enter amount in dollars."

Also need your help on this one: I can't get NVDA to read the "Approved 90% column" that is not a form field. There isn't any screenreader text here when I inspect the code, either.

**Comment by tbolt** [comment]
@jeromeleecms good catch ill look into those issues

**Comment by tbolt** [comment]
@jeromeleecms Updated the aria-labels. Let me know if you see any remaining issues with them.

For the "Approved 90% column" I am not able to get NVDA to navigate to that column either. The tab-navigation is going from form field to form field which is correct but I can't seem to get arrow navigation to move around the table.

**Comment by jeromeleecms** [comment]
@tbolt Can the column that is not a form field have a better descriptor when it is a read? Right now, all it reads is the dollar value with no reference to the column header. I still can't get it to read the table in order, but when I mouse over it, it doesn't give any information from a column/row standpoint. Not sure who else we can ask for help about reading columns...

Other than that the new aria labels are great.

**Comment by tbolt** [comment]
@jeromeleecms I will look into it. This is the first time I've seen forms embedded into a table and I am not finding much info around that pattern. I think we can at least have it read the associate column headers by using an aria-labelledby attribute.

**Comment by jeromeleecms** [comment]
Thanks for the reference on accessbility @Ty. Before I approve, it looks like there is some branch conflicts that need to be resolved. Did you talk to @thetif about a process to make sure we aren't merging old code in? The time out message is no longer a modal in this branch.

**Review by jeromeleecms — APPROVED** [review]
Alright, looks like from an accessibility standpoint, we are doing what we can and the changes to the table are good - so 👍

**Review by thetif — APPROVED** [review]

**Pull request merged**
