### PR TITLE
Knollfear/3030 switch states

### LINKED ISSUE #3030: [Dev] Create an endpoint for selecting an available state
Users can have multiple affiliations. Create an endpoint for a use to select one of those affiliations to use.

### This task is done when…
 - [ ] an endpoint exists to select an affiliation
 - [ ] update the JWT so that it reflects the user's role and activities for that affiliation

### PR DESCRIPTION
**Pull request by knollfear**
resolves #3030

**Description-**

**This pull request changes...**

- creates an endpoint (auth/state/:stateId) to change your active state

**This pull request also touches…**

- This should be isolated to just this endpoint

**This pull request was tested in the follow ways…**

- automated tests were created

**Steps to manually verify this change...**

1. Login to the app (ideally as a user with multiple states)
2. capture the authentication token by watching the network panel
3. paste that token in to jwt.io to see the claims.  Pay special attention to the state and states values
4. Using your favorite request tool (I like postman) make a request to /auth/state/md (use a state that you have in the list of states in the JWT)
5. get a response in the form of {jwt:<SOME_JWT>} and copy the jwt back to jwt.io and see that the states claim has changed.  The permissions may change as well if you have a different role in the new state.

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [x] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Looks good. I could decode the JWT to see the state properties. Nice work.

**Comment by thetif** [comment]
@knollfear I was unable to switch to a state that was pending. Can you please update to allow for this? Also, make sure that you can switch to a revoked/denied state too.

**Comment by thetif** [comment]
Also I'm unable to login as a sysadmin, but I'm not really sure why. I just get a 401 error on the /me endpoint, but no errors.

**Comment by knollfear** [comment]
> @knollfear it looks like it looks like jwtUtils.changeState is using getStateProfile instead of getStateById. But getStateProfile, just returns the medicaid office and not the state information, so it's getting a "Cannot set property 'id' of null" error.
> 
> Screen Shot 2021-06-14 at 12 56 48 PM

good call.  I switched it in this commit  https://github.com/CMSgov/eAPD/pull/3193/commits/1299c5bd5ab5c78a55e57aae4efb29c25da06a6e

**Review by thetif — APPROVED** [review]

**Comment by thetif** [comment]
works as expected, ready to merge

**Review by jeromeleecms — APPROVED** [review]
@thetif seems good with this. Was able to test the jwt token piece and it seems fine.

**Pull request merged**
