### PR TITLE
more changes to CSP

### PR DESCRIPTION
**Pull request by thetif**
spent some more time looking into CSP and tried to hopefully get it right this time....? 

### This pull request changes...

- changed CSP again

### This pull request is ready to merge when...

~- [ ] Tests have been updated (and all tests are passing)~
~- [ ] This code has been reviewed by someone other than the original author~
~- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented~
~- [ ] The change has been documented~
~- [ ] Associated OpenAPI documentation has been updated~
~- [ ] Changelog is updated as appropriate~

### CODE REVIEW

**Review by jeromeleecms — APPROVED** [review]
Looks good to me.

**Review by cthulhuplus — COMMENTED** [review]
Does "style-src ${gf}" need a trailing semi-colon?

**Comment by thetif** [comment]
I don't think you need a trailing semi-colon, I think that's only a delimiter

**Comment by thetif** [comment]
this time I put it through a CSP tester so I hope I caught issues

**Pull request merged**
