### PR TITLE
bbrooks/3103-Mongo_Staging

### PR DESCRIPTION
**Pull request by cthulhuplus**
Resolves # 3102 & 3103

**Description-**
Provisions a Mongo EC2 Instance for both Staging and Production with supported activities, Mongo AMI Packer build, Mongo Terraform, etc...

**This pull request changes...**

- Packer; adds Mongo AMI definition, Mongo provisioning script, updates Preview AMI from "eAPD Platinum AMI" to "eAPD Preview AMI"
- Terraform; reorganized into legacy and greenfield directories with sub directories, created files for legacy account environments; main, public, prod, staging, preview

**This pull request also touches…**
Git Ignore, AWS user data script

- possible side effects of this change

**This pull request was tested in the follow ways…**

- list of frontend cases
- list of backend cases

**Steps to manually verify this change...**

1. Do mongo stuff against the Mongo servers

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by cthulhuplus** [comment]
» terraform plan                                                                                                                                                                               1 ↵ bbrooks@Beast

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.eAPD.aws_instance.eapd_mongo_staging will be created
  + resource "aws_instance" "eapd_mongo_staging" {
      + ami                                  = "ami-0ca43bc063f64efe3"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "m3.medium"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "eapd_bbrooks"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = "subnet-07e1b9ed6ed5fb8c7"
      + tags                                 = {
          + "Environment"              = "staging"
          + "Name"                     = "eAPD Staging MongoDB"
          + "Patch Group"              = "RHEL7"
          + "Patch Window"             = "ITOPS-Wave1-Non-Mktplc-Prod-MW"
          + "Terraform"                = "True"
          + "cms-cloud-exempt:open-sg" = "CLDSPT-5877"
        }
      + tags_all                             = {
          + "Environment"              = "staging"
          + "Name"                     = "eAPD Staging MongoDB"
          + "Patch Group"              = "RHEL7"
          + "Patch Window"             = "ITOPS-Wave1-Non-Mktplc-Prod-MW"
          + "Terraform"                = "True"
          + "cms-cloud-exempt:open-sg" = "CLDSPT-5877"
        }
      + tenancy                              = (known after apply)
      + user_data                            = "8cf9c19d7efafccfdf924069906c53292f0c9ca9"
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = [
          + "eapd-staging-mongo-ec2",
          + "sg-01e01435dbbe6ce32",
        ]

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # module.eAPD.aws_security_group.eapd-staging-mongo-ec2 will be created
  + resource "aws_security_group" "eapd-staging-mongo-ec2" {
      + arn                    = (known after apply)
      + description            = "Mongo instance security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = []
              + description      = "Mongo Traffic from Jumpbox"
              + from_port        = 27017
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = [
                  + "sg-0f3c6bfa62fcefa4a",
                ]
              + self             = false
              + to_port          = 27019
            },
          + {
              + cidr_blocks      = []
              + description      = "SSH Access from Jumpbox"
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = [
                  + "sg-0f3c6bfa62fcefa4a",
                ]
              + self             = false
              + to_port          = 22
            },
        ]
      + name                   = "eapd-staging-mongo-ec2"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name"      = "eapd-staging-mongo-ec2"
          + "Terraform" = "Yes"
        }
      + tags_all               = {
          + "Name"      = "eapd-staging-mongo-ec2"
          + "Terraform" = "Yes"
        }
      + vpc_id                 = "vpc-00a77739f6d1c4175"
    }

Plan: 2 to add, 0 to change, 0 to destroy.

**Comment by cthulhuplus** [comment]
```
terraform apply                                                                 bbrooks@Beast

Terraform used the selected providers to generate the following execution plan. Resource
actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.eAPD.aws_instance.eapd_mongo_staging will be created
  + resource "aws_instance" "eapd_mongo_staging" {
      + ami                                  = "ami-0ca43bc063f64efe3"
      + arn                                  = (known after apply)
      + associate_public_ip_address          = (known after apply)
      + availability_zone                    = (known after apply)
      + cpu_core_count                       = (known after apply)
      + cpu_threads_per_core                 = (known after apply)
      + disable_api_termination              = (known after apply)
      + ebs_optimized                        = (known after apply)
      + get_password_data                    = false
      + host_id                              = (known after apply)
      + id                                   = (known after apply)
      + instance_initiated_shutdown_behavior = (known after apply)
      + instance_state                       = (known after apply)
      + instance_type                        = "m3.medium"
      + ipv6_address_count                   = (known after apply)
      + ipv6_addresses                       = (known after apply)
      + key_name                             = "eapd_bbrooks"
      + monitoring                           = (known after apply)
      + outpost_arn                          = (known after apply)
      + password_data                        = (known after apply)
      + placement_group                      = (known after apply)
      + placement_partition_number           = (known after apply)
      + primary_network_interface_id         = (known after apply)
      + private_dns                          = (known after apply)
      + private_ip                           = (known after apply)
      + public_dns                           = (known after apply)
      + public_ip                            = (known after apply)
      + secondary_private_ips                = (known after apply)
      + security_groups                      = (known after apply)
      + source_dest_check                    = true
      + subnet_id                            = "subnet-07e1b9ed6ed5fb8c7"
      + tags                                 = {
          + "Environment"              = "staging"
          + "Name"                     = "eAPD Staging MongoDB"
          + "Patch Group"              = "RHEL7"
          + "Patch Window"             = "ITOPS-Wave1-Non-Mktplc-Prod-MW"
          + "Terraform"                = "True"
          + "cms-cloud-exempt:open-sg" = "CLDSPT-5877"
        }
      + tags_all                             = {
          + "Environment"              = "staging"
          + "Name"                     = "eAPD Staging MongoDB"
          + "Patch Group"              = "RHEL7"
          + "Patch Window"             = "ITOPS-Wave1-Non-Mktplc-Prod-MW"
          + "Terraform"                = "True"
          + "cms-cloud-exempt:open-sg" = "CLDSPT-5877"
        }
      + tenancy                              = (known after apply)
      + user_data                            = "8cf9c19d7efafccfdf924069906c53292f0c9ca9"
      + user_data_base64                     = (known after apply)
      + vpc_security_group_ids               = (known after apply)

      + capacity_reservation_specification {
          + capacity_reservation_preference = (known after apply)

          + capacity_reservation_target {
              + capacity_reservation_id = (known after apply)
            }
        }

      + ebs_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + snapshot_id           = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }

      + enclave_options {
          + enabled = (known after apply)
        }

      + ephemeral_block_device {
          + device_name  = (known after apply)
          + no_device    = (known after apply)
          + virtual_name = (known after apply)
        }

      + metadata_options {
          + http_endpoint               = (known after apply)
          + http_put_response_hop_limit = (known after apply)
          + http_tokens                 = (known after apply)
        }

      + network_interface {
          + delete_on_termination = (known after apply)
          + device_index          = (known after apply)
          + network_interface_id  = (known after apply)
        }

      + root_block_device {
          + delete_on_termination = (known after apply)
          + device_name           = (known after apply)
          + encrypted             = (known after apply)
          + iops                  = (known after apply)
          + kms_key_id            = (known after apply)
          + tags                  = (known after apply)
          + throughput            = (known after apply)
          + volume_id             = (known after apply)
          + volume_size           = (known after apply)
          + volume_type           = (known after apply)
        }
    }

  # module.eAPD.aws_security_group.eapd-staging-mongo-ec2 will be created
  + resource "aws_security_group" "eapd-staging-mongo-ec2" {
      + arn                    = (known after apply)
      + description            = "Mongo instance security group"
      + egress                 = [
          + {
              + cidr_blocks      = [
                  + "0.0.0.0/0",
                ]
              + description      = ""
              + from_port        = 0
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "-1"
              + security_groups  = []
              + self             = false
              + to_port          = 0
            },
        ]
      + id                     = (known after apply)
      + ingress                = [
          + {
              + cidr_blocks      = []
              + description      = "Mongo Traffic from Jumpbox"
              + from_port        = 27017
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = [
                  + "sg-0f3c6bfa62fcefa4a",
                ]
              + self             = false
              + to_port          = 27019
            },
          + {
              + cidr_blocks      = []
              + description      = "SSH Access from Jumpbox"
              + from_port        = 22
              + ipv6_cidr_blocks = []
              + prefix_list_ids  = []
              + protocol         = "tcp"
              + security_groups  = [
                  + "sg-0f3c6bfa62fcefa4a",
                ]
              + self             = false
              + to_port          = 22
            },
        ]
      + name                   = "eapd-staging-mongo-ec2"
      + name_prefix            = (known after apply)
      + owner_id               = (known after apply)
      + revoke_rules_on_delete = false
      + tags                   = {
          + "Name"      = "eapd-staging-mongo-ec2"
          + "Terraform" = "Yes"
        }
      + tags_all               = {
          + "Name"      = "eapd-staging-mongo-ec2"
          + "Terraform" = "Yes"
        }
      + vpc_id                 = "vpc-00a77739f6d1c4175"
    }

Plan: 2 to add, 0 to change, 0 to destroy.
```

**Comment by cthulhuplus** [comment]
Before merging into main, line 104 of packer/mongo.sh needs to be updated to pull single branch from main.

**Review by thetif — APPROVED** [review]
looks good as far as I can tell

**Review by tbolt — APPROVED** [review]
This looks good to me

**Pull request merged**
