### PR TITLE
Knollfear/3386 default select values

### LINKED ISSUE #3386: [Bug] Dropdown menus should have a neutral selection.
**Description-**
Throughout the system, when we use the dropdown box component, there is no neutral selection option. We default to the top selection. This may cause users to not make a selection, and report information incorrectly.  

**Type of Bug-**

- [X] Accessibility
- [X] Functional
- [X] Usability
- [ ] API
- [ ] Regression

**Steps to reproduce-**

This happens in three places: 
1) In the FFP, Federal-State Split dropdown on the Budget and FFP page
2) In the non-personnel cost category, in an Activity on the State staff and expenses page
3) In the state and federal admin panels

**Role Affected-**

- [X] All
- [ ] Federal Admin
- [ ] State Admin
- [ ] State Staff
- [ ] State Contractor
- [ ] System Admin

**Environment-**

- [X] All
- [ ] PR #\_\_\_\_
- [ ] Staging
- [ ] Production

**Browser-**

- [ ] Firefox
- [X] Chrome
- [ ] IE

**Expected results-**
A neutral selection should be available to users. This should match to the cms design system component. https://design.cms.gov/components/dropdown/ as "Select an option"

**Actual results-**
A default selection is made any time the drop down menu is accessed as "Select an option" isn't available. 

**Related user story/bug-** (if applicable)

**Additional information-** (optional)

**Logs or error output/Screenshot/Video-** (at least 1 of these)

### PR DESCRIPTION
**Pull request by knollfear**
resolves #3386

**Description-**

**This pull request changes...**
1) In the FFP, Federal-State Split dropdown on the Budget and FFP page
    State split is initially set to 100% state and 0% federal.  If users make a selection then the state will pay less than the full cost.
2) In the non-personnel cost category, in an Activity on the State staff and expenses page
    When a non-personnel cost is added it will have no category and display as "Category not selected" in the list 
3) In the state and federal admin panels when a user is granted access (either new access or restoring revoked access).
I did not stop the form from submitting when no choice was made.  It will just fail and not approve the user.

**This pull request also touches…**

- possible side effects of this change

**This pull request was tested in the follow ways…**

- manually checked that newly created objects show the "make a selection" option.

**Steps to manually verify this change...**

1. add an activity to an APD
2. edit the apd
3. go to "Budget and FFP"
4. look for federal state split to confirm it is 100% state
5. go to "State Staff and Expenses"
6. click "Add State Expense"
7. confirm no category is chosen

1. log in as a state admin
2. go to the state administrator portal
3. on requests or inactive click to grant access
4. no role should be selected
5. on the active tab if you click edit role, a role SHOULD be selected

### This pull request is ready to review when...

- [ ] Automated tests are updated (and all tests are passing)
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screenreader, text scaling) OR an exemption is documented

### This pull request can be merged when…

- [ ] Code has been reviewed by someone other than the original author
- [ ] QA has verified the accessibility and functionality related to the change
- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by jeromeleecms — CHANGES_REQUESTED** [review]
When no option is selected in the "Other State Expenses," the table is not showing a "Category Not Selected" in the builder or export view of the "Budget Table" in the activity or in the activity breakdown: 

image

Everything else seems to function as advertised.

**Comment by knollfear** [comment]
> When no option is selected in the "Other State Expenses," the table is not showing a "Category Not Selected" in the builder or export view of the "Budget Table" in the activity or in the activity breakdown:
> 
> image
> 
> Everything else seems to function as advertised.

This has been resolved and a fix is incoming.  When this PR is redeployed you should be able to see it.

**Review by jeromeleecms — APPROVED** [review]
Looks good now. Thank you.

**Comment by beparticular** [comment]
@knollfear it's looking like in the admin panel, if a user exists in the Active tab, and I want to edit their role - I select the 'select an option' option and save - then the role doesn't change. Is that intentional since I'm guessing we don't have a "no role" role?

**Comment by knollfear** [comment]
> @knollfear it's looking like in the admin panel, if a user exists in the Active tab, and I want to edit their role - I select the 'select an option' option and save - then the role doesn't change. Is that intentional since I'm guessing we don't have a "no role" role?

It is intentional because we can't do much else.  The only other thing I could do is give them a validation warning along the lines of "Please select a role" (which feels like part of the bigger validation piece) or I could disable the save button if no role is selected.  Let me know what works best for you and I can do it.

**Comment by beparticular** [comment]
@knollfear why don't we add a ticket for it under the validation epic and we can address it there? 
@jeromeleecms is that good with you?

**Review by beparticular — APPROVED** [review]

**Pull request merged**
